// Generated by delombok at Wed Jun 17 17:25:54 CST 2026
package com.edu.agent.module.knowledge.entity;

import com.edu.agent.common.base.BaseEntity;
import com.baomidou.mybatisplus.annotation.TableName;

@TableName("knowledge_base")
public class KnowledgeBase extends BaseEntity {
    private Long courseId;
    private Long uploadedBy;
    private String name;
    private String description;
    private String filePath;
    private String fileType;
    private Long fileSize;
    private Integer status; // 0=pending, 1=indexed, 2=failed
    private String approvalStatus; // PENDING/APPROVED/REJECTED
    private String approvalRemark;

    @java.lang.SuppressWarnings("all")
    public KnowledgeBase() {
    }

    @java.lang.SuppressWarnings("all")
    public Long getCourseId() {
        return this.courseId;
    }

    @java.lang.SuppressWarnings("all")
    public Long getUploadedBy() {
        return this.uploadedBy;
    }

    @java.lang.SuppressWarnings("all")
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    public String getDescription() {
        return this.description;
    }

    @java.lang.SuppressWarnings("all")
    public String getFilePath() {
        return this.filePath;
    }

    @java.lang.SuppressWarnings("all")
    public String getFileType() {
        return this.fileType;
    }

    @java.lang.SuppressWarnings("all")
    public Long getFileSize() {
        return this.fileSize;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    public String getApprovalStatus() {
        return this.approvalStatus;
    }

    @java.lang.SuppressWarnings("all")
    public String getApprovalRemark() {
        return this.approvalRemark;
    }

    @java.lang.SuppressWarnings("all")
    public void setCourseId(final Long courseId) {
        this.courseId = courseId;
    }

    @java.lang.SuppressWarnings("all")
    public void setUploadedBy(final Long uploadedBy) {
        this.uploadedBy = uploadedBy;
    }

    @java.lang.SuppressWarnings("all")
    public void setName(final String name) {
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    public void setDescription(final String description) {
        this.description = description;
    }

    @java.lang.SuppressWarnings("all")
    public void setFilePath(final String filePath) {
        this.filePath = filePath;
    }

    @java.lang.SuppressWarnings("all")
    public void setFileType(final String fileType) {
        this.fileType = fileType;
    }

    @java.lang.SuppressWarnings("all")
    public void setFileSize(final Long fileSize) {
        this.fileSize = fileSize;
    }

    @java.lang.SuppressWarnings("all")
    public void setStatus(final Integer status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    public void setApprovalStatus(final String approvalStatus) {
        this.approvalStatus = approvalStatus;
    }

    @java.lang.SuppressWarnings("all")
    public void setApprovalRemark(final String approvalRemark) {
        this.approvalRemark = approvalRemark;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "KnowledgeBase(courseId=" + this.getCourseId() + ", uploadedBy=" + this.getUploadedBy() + ", name=" + this.getName() + ", description=" + this.getDescription() + ", filePath=" + this.getFilePath() + ", fileType=" + this.getFileType() + ", fileSize=" + this.getFileSize() + ", status=" + this.getStatus() + ", approvalStatus=" + this.getApprovalStatus() + ", approvalRemark=" + this.getApprovalRemark() + ")";
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof KnowledgeBase)) return false;
        final KnowledgeBase other = (KnowledgeBase) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (!super.equals(o)) return false;
        final java.lang.Object this$courseId = this.getCourseId();
        final java.lang.Object other$courseId = other.getCourseId();
        if (this$courseId == null ? other$courseId != null : !this$courseId.equals(other$courseId)) return false;
        final java.lang.Object this$uploadedBy = this.getUploadedBy();
        final java.lang.Object other$uploadedBy = other.getUploadedBy();
        if (this$uploadedBy == null ? other$uploadedBy != null : !this$uploadedBy.equals(other$uploadedBy)) return false;
        final java.lang.Object this$fileSize = this.getFileSize();
        final java.lang.Object other$fileSize = other.getFileSize();
        if (this$fileSize == null ? other$fileSize != null : !this$fileSize.equals(other$fileSize)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        final java.lang.Object this$name = this.getName();
        final java.lang.Object other$name = other.getName();
        if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
        final java.lang.Object this$description = this.getDescription();
        final java.lang.Object other$description = other.getDescription();
        if (this$description == null ? other$description != null : !this$description.equals(other$description)) return false;
        final java.lang.Object this$filePath = this.getFilePath();
        final java.lang.Object other$filePath = other.getFilePath();
        if (this$filePath == null ? other$filePath != null : !this$filePath.equals(other$filePath)) return false;
        final java.lang.Object this$fileType = this.getFileType();
        final java.lang.Object other$fileType = other.getFileType();
        if (this$fileType == null ? other$fileType != null : !this$fileType.equals(other$fileType)) return false;
        final java.lang.Object this$approvalStatus = this.getApprovalStatus();
        final java.lang.Object other$approvalStatus = other.getApprovalStatus();
        if (this$approvalStatus == null ? other$approvalStatus != null : !this$approvalStatus.equals(other$approvalStatus)) return false;
        final java.lang.Object this$approvalRemark = this.getApprovalRemark();
        final java.lang.Object other$approvalRemark = other.getApprovalRemark();
        if (this$approvalRemark == null ? other$approvalRemark != null : !this$approvalRemark.equals(other$approvalRemark)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof KnowledgeBase;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = super.hashCode();
        final java.lang.Object $courseId = this.getCourseId();
        result = result * PRIME + ($courseId == null ? 43 : $courseId.hashCode());
        final java.lang.Object $uploadedBy = this.getUploadedBy();
        result = result * PRIME + ($uploadedBy == null ? 43 : $uploadedBy.hashCode());
        final java.lang.Object $fileSize = this.getFileSize();
        result = result * PRIME + ($fileSize == null ? 43 : $fileSize.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        final java.lang.Object $name = this.getName();
        result = result * PRIME + ($name == null ? 43 : $name.hashCode());
        final java.lang.Object $description = this.getDescription();
        result = result * PRIME + ($description == null ? 43 : $description.hashCode());
        final java.lang.Object $filePath = this.getFilePath();
        result = result * PRIME + ($filePath == null ? 43 : $filePath.hashCode());
        final java.lang.Object $fileType = this.getFileType();
        result = result * PRIME + ($fileType == null ? 43 : $fileType.hashCode());
        final java.lang.Object $approvalStatus = this.getApprovalStatus();
        result = result * PRIME + ($approvalStatus == null ? 43 : $approvalStatus.hashCode());
        final java.lang.Object $approvalRemark = this.getApprovalRemark();
        result = result * PRIME + ($approvalRemark == null ? 43 : $approvalRemark.hashCode());
        return result;
    }
}
