// Generated by delombok at Wed Jun 17 17:25:54 CST 2026
package com.edu.agent.module.schedule.entity;

import com.edu.agent.common.base.BaseEntity;
import com.baomidou.mybatisplus.annotation.TableName;

@TableName("schedule_course")
public class ScheduleCourse extends BaseEntity {
    private Long userId;
    private String name;
    /**
     * JSON: [1,2,3,...]
     */
    private String weekNumbers;
    /**
     * JSON: [1,2,3,4,5,6,7] 1=周一
     */
    private String dayOfWeeks;
    /**
     * JSON: [0,1,2,...]
     */
    private String periodIndexes;

    @java.lang.SuppressWarnings("all")
    public ScheduleCourse() {
    }

    @java.lang.SuppressWarnings("all")
    public Long getUserId() {
        return this.userId;
    }

    @java.lang.SuppressWarnings("all")
    public String getName() {
        return this.name;
    }

    /**
     * JSON: [1,2,3,...]
     */
    @java.lang.SuppressWarnings("all")
    public String getWeekNumbers() {
        return this.weekNumbers;
    }

    /**
     * JSON: [1,2,3,4,5,6,7] 1=周一
     */
    @java.lang.SuppressWarnings("all")
    public String getDayOfWeeks() {
        return this.dayOfWeeks;
    }

    /**
     * JSON: [0,1,2,...]
     */
    @java.lang.SuppressWarnings("all")
    public String getPeriodIndexes() {
        return this.periodIndexes;
    }

    @java.lang.SuppressWarnings("all")
    public void setUserId(final Long userId) {
        this.userId = userId;
    }

    @java.lang.SuppressWarnings("all")
    public void setName(final String name) {
        this.name = name;
    }

    /**
     * JSON: [1,2,3,...]
     */
    @java.lang.SuppressWarnings("all")
    public void setWeekNumbers(final String weekNumbers) {
        this.weekNumbers = weekNumbers;
    }

    /**
     * JSON: [1,2,3,4,5,6,7] 1=周一
     */
    @java.lang.SuppressWarnings("all")
    public void setDayOfWeeks(final String dayOfWeeks) {
        this.dayOfWeeks = dayOfWeeks;
    }

    /**
     * JSON: [0,1,2,...]
     */
    @java.lang.SuppressWarnings("all")
    public void setPeriodIndexes(final String periodIndexes) {
        this.periodIndexes = periodIndexes;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "ScheduleCourse(userId=" + this.getUserId() + ", name=" + this.getName() + ", weekNumbers=" + this.getWeekNumbers() + ", dayOfWeeks=" + this.getDayOfWeeks() + ", periodIndexes=" + this.getPeriodIndexes() + ")";
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof ScheduleCourse)) return false;
        final ScheduleCourse other = (ScheduleCourse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (!super.equals(o)) return false;
        final java.lang.Object this$userId = this.getUserId();
        final java.lang.Object other$userId = other.getUserId();
        if (this$userId == null ? other$userId != null : !this$userId.equals(other$userId)) return false;
        final java.lang.Object this$name = this.getName();
        final java.lang.Object other$name = other.getName();
        if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
        final java.lang.Object this$weekNumbers = this.getWeekNumbers();
        final java.lang.Object other$weekNumbers = other.getWeekNumbers();
        if (this$weekNumbers == null ? other$weekNumbers != null : !this$weekNumbers.equals(other$weekNumbers)) return false;
        final java.lang.Object this$dayOfWeeks = this.getDayOfWeeks();
        final java.lang.Object other$dayOfWeeks = other.getDayOfWeeks();
        if (this$dayOfWeeks == null ? other$dayOfWeeks != null : !this$dayOfWeeks.equals(other$dayOfWeeks)) return false;
        final java.lang.Object this$periodIndexes = this.getPeriodIndexes();
        final java.lang.Object other$periodIndexes = other.getPeriodIndexes();
        if (this$periodIndexes == null ? other$periodIndexes != null : !this$periodIndexes.equals(other$periodIndexes)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof ScheduleCourse;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = super.hashCode();
        final java.lang.Object $userId = this.getUserId();
        result = result * PRIME + ($userId == null ? 43 : $userId.hashCode());
        final java.lang.Object $name = this.getName();
        result = result * PRIME + ($name == null ? 43 : $name.hashCode());
        final java.lang.Object $weekNumbers = this.getWeekNumbers();
        result = result * PRIME + ($weekNumbers == null ? 43 : $weekNumbers.hashCode());
        final java.lang.Object $dayOfWeeks = this.getDayOfWeeks();
        result = result * PRIME + ($dayOfWeeks == null ? 43 : $dayOfWeeks.hashCode());
        final java.lang.Object $periodIndexes = this.getPeriodIndexes();
        result = result * PRIME + ($periodIndexes == null ? 43 : $periodIndexes.hashCode());
        return result;
    }
}
