// Generated by delombok at Wed Jun 17 17:25:54 CST 2026
package com.edu.agent.module.schedule.entity;

import com.edu.agent.common.base.BaseEntity;
import com.baomidou.mybatisplus.annotation.TableName;
import java.time.LocalDate;

@TableName("schedule_config")
public class ScheduleConfig extends BaseEntity {
    private Long userId;
    private LocalDate semesterStartDate;
    /**
     * JSON: [{name, startTime, endTime}]
     */
    private String periodConfig;

    @java.lang.SuppressWarnings("all")
    public ScheduleConfig() {
    }

    @java.lang.SuppressWarnings("all")
    public Long getUserId() {
        return this.userId;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDate getSemesterStartDate() {
        return this.semesterStartDate;
    }

    /**
     * JSON: [{name, startTime, endTime}]
     */
    @java.lang.SuppressWarnings("all")
    public String getPeriodConfig() {
        return this.periodConfig;
    }

    @java.lang.SuppressWarnings("all")
    public void setUserId(final Long userId) {
        this.userId = userId;
    }

    @java.lang.SuppressWarnings("all")
    public void setSemesterStartDate(final LocalDate semesterStartDate) {
        this.semesterStartDate = semesterStartDate;
    }

    /**
     * JSON: [{name, startTime, endTime}]
     */
    @java.lang.SuppressWarnings("all")
    public void setPeriodConfig(final String periodConfig) {
        this.periodConfig = periodConfig;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "ScheduleConfig(userId=" + this.getUserId() + ", semesterStartDate=" + this.getSemesterStartDate() + ", periodConfig=" + this.getPeriodConfig() + ")";
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof ScheduleConfig)) return false;
        final ScheduleConfig other = (ScheduleConfig) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (!super.equals(o)) return false;
        final java.lang.Object this$userId = this.getUserId();
        final java.lang.Object other$userId = other.getUserId();
        if (this$userId == null ? other$userId != null : !this$userId.equals(other$userId)) return false;
        final java.lang.Object this$semesterStartDate = this.getSemesterStartDate();
        final java.lang.Object other$semesterStartDate = other.getSemesterStartDate();
        if (this$semesterStartDate == null ? other$semesterStartDate != null : !this$semesterStartDate.equals(other$semesterStartDate)) return false;
        final java.lang.Object this$periodConfig = this.getPeriodConfig();
        final java.lang.Object other$periodConfig = other.getPeriodConfig();
        if (this$periodConfig == null ? other$periodConfig != null : !this$periodConfig.equals(other$periodConfig)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof ScheduleConfig;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = super.hashCode();
        final java.lang.Object $userId = this.getUserId();
        result = result * PRIME + ($userId == null ? 43 : $userId.hashCode());
        final java.lang.Object $semesterStartDate = this.getSemesterStartDate();
        result = result * PRIME + ($semesterStartDate == null ? 43 : $semesterStartDate.hashCode());
        final java.lang.Object $periodConfig = this.getPeriodConfig();
        result = result * PRIME + ($periodConfig == null ? 43 : $periodConfig.hashCode());
        return result;
    }
}
