// Generated by delombok at Wed Jun 17 17:25:54 CST 2026
package com.edu.agent.module.learning.entity;

import com.edu.agent.common.base.BaseEntity;
import com.baomidou.mybatisplus.annotation.TableName;

@TableName("learning_path_step")
public class LearningPathStep extends BaseEntity {
    private Long pathId;
    private Integer stepOrder;
    private String title;
    private String description;
    private Long knowledgeBaseId;
    private Integer status; // 0=pending, 1=in_progress, 2=completed
    private String stepType; // CONCEPT/PRACTICE/REVIEW/PROJECT
    private Integer estimatedHours;

    @java.lang.SuppressWarnings("all")
    public LearningPathStep() {
    }

    @java.lang.SuppressWarnings("all")
    public Long getPathId() {
        return this.pathId;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getStepOrder() {
        return this.stepOrder;
    }

    @java.lang.SuppressWarnings("all")
    public String getTitle() {
        return this.title;
    }

    @java.lang.SuppressWarnings("all")
    public String getDescription() {
        return this.description;
    }

    @java.lang.SuppressWarnings("all")
    public Long getKnowledgeBaseId() {
        return this.knowledgeBaseId;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    public String getStepType() {
        return this.stepType;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getEstimatedHours() {
        return this.estimatedHours;
    }

    @java.lang.SuppressWarnings("all")
    public void setPathId(final Long pathId) {
        this.pathId = pathId;
    }

    @java.lang.SuppressWarnings("all")
    public void setStepOrder(final Integer stepOrder) {
        this.stepOrder = stepOrder;
    }

    @java.lang.SuppressWarnings("all")
    public void setTitle(final String title) {
        this.title = title;
    }

    @java.lang.SuppressWarnings("all")
    public void setDescription(final String description) {
        this.description = description;
    }

    @java.lang.SuppressWarnings("all")
    public void setKnowledgeBaseId(final Long knowledgeBaseId) {
        this.knowledgeBaseId = knowledgeBaseId;
    }

    @java.lang.SuppressWarnings("all")
    public void setStatus(final Integer status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    public void setStepType(final String stepType) {
        this.stepType = stepType;
    }

    @java.lang.SuppressWarnings("all")
    public void setEstimatedHours(final Integer estimatedHours) {
        this.estimatedHours = estimatedHours;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "LearningPathStep(pathId=" + this.getPathId() + ", stepOrder=" + this.getStepOrder() + ", title=" + this.getTitle() + ", description=" + this.getDescription() + ", knowledgeBaseId=" + this.getKnowledgeBaseId() + ", status=" + this.getStatus() + ")";
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof LearningPathStep)) return false;
        final LearningPathStep other = (LearningPathStep) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (!super.equals(o)) return false;
        final java.lang.Object this$pathId = this.getPathId();
        final java.lang.Object other$pathId = other.getPathId();
        if (this$pathId == null ? other$pathId != null : !this$pathId.equals(other$pathId)) return false;
        final java.lang.Object this$stepOrder = this.getStepOrder();
        final java.lang.Object other$stepOrder = other.getStepOrder();
        if (this$stepOrder == null ? other$stepOrder != null : !this$stepOrder.equals(other$stepOrder)) return false;
        final java.lang.Object this$knowledgeBaseId = this.getKnowledgeBaseId();
        final java.lang.Object other$knowledgeBaseId = other.getKnowledgeBaseId();
        if (this$knowledgeBaseId == null ? other$knowledgeBaseId != null : !this$knowledgeBaseId.equals(other$knowledgeBaseId)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        final java.lang.Object this$title = this.getTitle();
        final java.lang.Object other$title = other.getTitle();
        if (this$title == null ? other$title != null : !this$title.equals(other$title)) return false;
        final java.lang.Object this$description = this.getDescription();
        final java.lang.Object other$description = other.getDescription();
        if (this$description == null ? other$description != null : !this$description.equals(other$description)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof LearningPathStep;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = super.hashCode();
        final java.lang.Object $pathId = this.getPathId();
        result = result * PRIME + ($pathId == null ? 43 : $pathId.hashCode());
        final java.lang.Object $stepOrder = this.getStepOrder();
        result = result * PRIME + ($stepOrder == null ? 43 : $stepOrder.hashCode());
        final java.lang.Object $knowledgeBaseId = this.getKnowledgeBaseId();
        result = result * PRIME + ($knowledgeBaseId == null ? 43 : $knowledgeBaseId.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        final java.lang.Object $title = this.getTitle();
        result = result * PRIME + ($title == null ? 43 : $title.hashCode());
        final java.lang.Object $description = this.getDescription();
        result = result * PRIME + ($description == null ? 43 : $description.hashCode());
        return result;
    }
}
