// Generated by delombok at Wed Jun 17 17:25:54 CST 2026
package com.edu.agent.module.learning.entity;

import com.baomidou.mybatisplus.annotation.TableName;
import com.edu.agent.common.base.BaseEntity;

@TableName("student_profile_questionnaire")
public class StudentProfileQuestionnaire extends BaseEntity {
    private Long userId;
    private String questionnaireData; // JSON string for MyBatis-Plus
    private Integer isCompleted; // 0=未完成 1=已完成

    @java.lang.SuppressWarnings("all")
    public StudentProfileQuestionnaire() {
    }

    @java.lang.SuppressWarnings("all")
    public Long getUserId() {
        return this.userId;
    }

    @java.lang.SuppressWarnings("all")
    public String getQuestionnaireData() {
        return this.questionnaireData;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getIsCompleted() {
        return this.isCompleted;
    }

    @java.lang.SuppressWarnings("all")
    public void setUserId(final Long userId) {
        this.userId = userId;
    }

    @java.lang.SuppressWarnings("all")
    public void setQuestionnaireData(final String questionnaireData) {
        this.questionnaireData = questionnaireData;
    }

    @java.lang.SuppressWarnings("all")
    public void setIsCompleted(final Integer isCompleted) {
        this.isCompleted = isCompleted;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "StudentProfileQuestionnaire(userId=" + this.getUserId() + ", questionnaireData=" + this.getQuestionnaireData() + ", isCompleted=" + this.getIsCompleted() + ")";
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof StudentProfileQuestionnaire)) return false;
        final StudentProfileQuestionnaire other = (StudentProfileQuestionnaire) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (!super.equals(o)) return false;
        final java.lang.Object this$userId = this.getUserId();
        final java.lang.Object other$userId = other.getUserId();
        if (this$userId == null ? other$userId != null : !this$userId.equals(other$userId)) return false;
        final java.lang.Object this$isCompleted = this.getIsCompleted();
        final java.lang.Object other$isCompleted = other.getIsCompleted();
        if (this$isCompleted == null ? other$isCompleted != null : !this$isCompleted.equals(other$isCompleted)) return false;
        final java.lang.Object this$questionnaireData = this.getQuestionnaireData();
        final java.lang.Object other$questionnaireData = other.getQuestionnaireData();
        if (this$questionnaireData == null ? other$questionnaireData != null : !this$questionnaireData.equals(other$questionnaireData)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof StudentProfileQuestionnaire;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = super.hashCode();
        final java.lang.Object $userId = this.getUserId();
        result = result * PRIME + ($userId == null ? 43 : $userId.hashCode());
        final java.lang.Object $isCompleted = this.getIsCompleted();
        result = result * PRIME + ($isCompleted == null ? 43 : $isCompleted.hashCode());
        final java.lang.Object $questionnaireData = this.getQuestionnaireData();
        result = result * PRIME + ($questionnaireData == null ? 43 : $questionnaireData.hashCode());
        return result;
    }
}
