// Generated by delombok at Wed Jun 17 17:25:54 CST 2026
package com.edu.agent.module.learning.entity;

import com.edu.agent.common.base.BaseEntity;
import com.baomidou.mybatisplus.annotation.TableName;

@TableName("student_profile")
public class StudentProfile extends BaseEntity {
    private Long userId;
    private String learningStyle; // VISUAL / AUDITORY / READING / KINESTHETIC
    private String strengths;
    private String weaknesses;
    private String interests;
    private String gradeLevel;
    private String preferences; // JSON

    @java.lang.SuppressWarnings("all")
    public StudentProfile() {
    }

    @java.lang.SuppressWarnings("all")
    public Long getUserId() {
        return this.userId;
    }

    @java.lang.SuppressWarnings("all")
    public String getLearningStyle() {
        return this.learningStyle;
    }

    @java.lang.SuppressWarnings("all")
    public String getStrengths() {
        return this.strengths;
    }

    @java.lang.SuppressWarnings("all")
    public String getWeaknesses() {
        return this.weaknesses;
    }

    @java.lang.SuppressWarnings("all")
    public String getInterests() {
        return this.interests;
    }

    @java.lang.SuppressWarnings("all")
    public String getGradeLevel() {
        return this.gradeLevel;
    }

    @java.lang.SuppressWarnings("all")
    public String getPreferences() {
        return this.preferences;
    }

    @java.lang.SuppressWarnings("all")
    public void setUserId(final Long userId) {
        this.userId = userId;
    }

    @java.lang.SuppressWarnings("all")
    public void setLearningStyle(final String learningStyle) {
        this.learningStyle = learningStyle;
    }

    @java.lang.SuppressWarnings("all")
    public void setStrengths(final String strengths) {
        this.strengths = strengths;
    }

    @java.lang.SuppressWarnings("all")
    public void setWeaknesses(final String weaknesses) {
        this.weaknesses = weaknesses;
    }

    @java.lang.SuppressWarnings("all")
    public void setInterests(final String interests) {
        this.interests = interests;
    }

    @java.lang.SuppressWarnings("all")
    public void setGradeLevel(final String gradeLevel) {
        this.gradeLevel = gradeLevel;
    }

    @java.lang.SuppressWarnings("all")
    public void setPreferences(final String preferences) {
        this.preferences = preferences;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "StudentProfile(userId=" + this.getUserId() + ", learningStyle=" + this.getLearningStyle() + ", strengths=" + this.getStrengths() + ", weaknesses=" + this.getWeaknesses() + ", interests=" + this.getInterests() + ", gradeLevel=" + this.getGradeLevel() + ", preferences=" + this.getPreferences() + ")";
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof StudentProfile)) return false;
        final StudentProfile other = (StudentProfile) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (!super.equals(o)) return false;
        final java.lang.Object this$userId = this.getUserId();
        final java.lang.Object other$userId = other.getUserId();
        if (this$userId == null ? other$userId != null : !this$userId.equals(other$userId)) return false;
        final java.lang.Object this$learningStyle = this.getLearningStyle();
        final java.lang.Object other$learningStyle = other.getLearningStyle();
        if (this$learningStyle == null ? other$learningStyle != null : !this$learningStyle.equals(other$learningStyle)) return false;
        final java.lang.Object this$strengths = this.getStrengths();
        final java.lang.Object other$strengths = other.getStrengths();
        if (this$strengths == null ? other$strengths != null : !this$strengths.equals(other$strengths)) return false;
        final java.lang.Object this$weaknesses = this.getWeaknesses();
        final java.lang.Object other$weaknesses = other.getWeaknesses();
        if (this$weaknesses == null ? other$weaknesses != null : !this$weaknesses.equals(other$weaknesses)) return false;
        final java.lang.Object this$interests = this.getInterests();
        final java.lang.Object other$interests = other.getInterests();
        if (this$interests == null ? other$interests != null : !this$interests.equals(other$interests)) return false;
        final java.lang.Object this$gradeLevel = this.getGradeLevel();
        final java.lang.Object other$gradeLevel = other.getGradeLevel();
        if (this$gradeLevel == null ? other$gradeLevel != null : !this$gradeLevel.equals(other$gradeLevel)) return false;
        final java.lang.Object this$preferences = this.getPreferences();
        final java.lang.Object other$preferences = other.getPreferences();
        if (this$preferences == null ? other$preferences != null : !this$preferences.equals(other$preferences)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof StudentProfile;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = super.hashCode();
        final java.lang.Object $userId = this.getUserId();
        result = result * PRIME + ($userId == null ? 43 : $userId.hashCode());
        final java.lang.Object $learningStyle = this.getLearningStyle();
        result = result * PRIME + ($learningStyle == null ? 43 : $learningStyle.hashCode());
        final java.lang.Object $strengths = this.getStrengths();
        result = result * PRIME + ($strengths == null ? 43 : $strengths.hashCode());
        final java.lang.Object $weaknesses = this.getWeaknesses();
        result = result * PRIME + ($weaknesses == null ? 43 : $weaknesses.hashCode());
        final java.lang.Object $interests = this.getInterests();
        result = result * PRIME + ($interests == null ? 43 : $interests.hashCode());
        final java.lang.Object $gradeLevel = this.getGradeLevel();
        result = result * PRIME + ($gradeLevel == null ? 43 : $gradeLevel.hashCode());
        final java.lang.Object $preferences = this.getPreferences();
        result = result * PRIME + ($preferences == null ? 43 : $preferences.hashCode());
        return result;
    }
}
