// Generated by delombok at Wed Jun 17 17:25:54 CST 2026
package com.edu.agent.common.exception;

import com.edu.agent.common.result.ResultCode;

/**
 * Business exception carrying a ResultCode.
 */
public class BizException extends RuntimeException {
    private static final long serialVersionUID = 1L;
    /**
     * Business error code
     */
    private final ResultCode resultCode;

    /**
     * Construct with a ResultCode.
     */
    public BizException(ResultCode resultCode) {
        super(resultCode.getMessage());
        this.resultCode = resultCode;
    }

    /**
     * Construct with a ResultCode and custom message.
     */
    public BizException(ResultCode resultCode, String message) {
        super(message);
        this.resultCode = resultCode;
    }

    /**
     * Construct with a ResultCode, custom message, and cause.
     */
    public BizException(ResultCode resultCode, String message, Throwable cause) {
        super(message, cause);
        this.resultCode = resultCode;
    }

    /**
     * Business error code
     */
    @java.lang.SuppressWarnings("all")
    public ResultCode getResultCode() {
        return this.resultCode;
    }
}
