// Generated by delombok
package com.edu.agent.module.user.dto;

import java.time.LocalDateTime;


public class UserProfileDTO {
    private Long id;
    private String username;
    private String nickname;
    private String email;
    private String phone;
    private String avatar;
    private String role;
    private Integer status;
    private LocalDateTime lastLoginTime;
    private Double totalStudyHours;
    private Integer courseCount;
    private Integer pathCount;
    private Integer chatCount;

    @java.lang.SuppressWarnings("all")
    public UserProfileDTO() {
    }

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public String getUsername() {
        return this.username;
    }

    @java.lang.SuppressWarnings("all")
    public String getNickname() {
        return this.nickname;
    }

    @java.lang.SuppressWarnings("all")
    public String getEmail() {
        return this.email;
    }

    @java.lang.SuppressWarnings("all")
    public String getPhone() {
        return this.phone;
    }

    @java.lang.SuppressWarnings("all")
    public String getAvatar() {
        return this.avatar;
    }

    @java.lang.SuppressWarnings("all")
    public String getRole() {
        return this.role;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getLastLoginTime() {
        return this.lastLoginTime;
    }

    @java.lang.SuppressWarnings("all")
    public Double getTotalStudyHours() {
        return this.totalStudyHours;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getCourseCount() {
        return this.courseCount;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getPathCount() {
        return this.pathCount;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getChatCount() {
        return this.chatCount;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setUsername(final String username) {
        this.username = username;
    }

    @java.lang.SuppressWarnings("all")
    public void setNickname(final String nickname) {
        this.nickname = nickname;
    }

    @java.lang.SuppressWarnings("all")
    public void setEmail(final String email) {
        this.email = email;
    }

    @java.lang.SuppressWarnings("all")
    public void setPhone(final String phone) {
        this.phone = phone;
    }

    @java.lang.SuppressWarnings("all")
    public void setAvatar(final String avatar) {
        this.avatar = avatar;
    }

    @java.lang.SuppressWarnings("all")
    public void setRole(final String role) {
        this.role = role;
    }

    @java.lang.SuppressWarnings("all")
    public void setStatus(final Integer status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    public void setLastLoginTime(final LocalDateTime lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    @java.lang.SuppressWarnings("all")
    public void setTotalStudyHours(final Double totalStudyHours) {
        this.totalStudyHours = totalStudyHours;
    }

    @java.lang.SuppressWarnings("all")
    public void setCourseCount(final Integer courseCount) {
        this.courseCount = courseCount;
    }

    @java.lang.SuppressWarnings("all")
    public void setPathCount(final Integer pathCount) {
        this.pathCount = pathCount;
    }

    @java.lang.SuppressWarnings("all")
    public void setChatCount(final Integer chatCount) {
        this.chatCount = chatCount;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "UserProfileDTO(" + "id=" + this.getId() + ", username=" + this.getUsername() + ", nickname=" + this.getNickname() + ", email=" + this.getEmail() + ", phone=" + this.getPhone() + ", avatar=" + this.getAvatar() + ", role=" + this.getRole() + ", status=" + this.getStatus() + ", lastLoginTime=" + this.getLastLoginTime() + ", totalStudyHours=" + this.getTotalStudyHours() + ", courseCount=" + this.getCourseCount() + ", pathCount=" + this.getPathCount() + ", chatCount=" + this.getChatCount() + ")";
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof UserProfileDTO)) return false;
        final UserProfileDTO other = (UserProfileDTO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$username = this.getUsername();
        final java.lang.Object other$username = other.getUsername();
        if (this$username == null ? other$username != null : !this$username.equals(other$username)) return false;
        final java.lang.Object this$nickname = this.getNickname();
        final java.lang.Object other$nickname = other.getNickname();
        if (this$nickname == null ? other$nickname != null : !this$nickname.equals(other$nickname)) return false;
        final java.lang.Object this$email = this.getEmail();
        final java.lang.Object other$email = other.getEmail();
        if (this$email == null ? other$email != null : !this$email.equals(other$email)) return false;
        final java.lang.Object this$phone = this.getPhone();
        final java.lang.Object other$phone = other.getPhone();
        if (this$phone == null ? other$phone != null : !this$phone.equals(other$phone)) return false;
        final java.lang.Object this$avatar = this.getAvatar();
        final java.lang.Object other$avatar = other.getAvatar();
        if (this$avatar == null ? other$avatar != null : !this$avatar.equals(other$avatar)) return false;
        final java.lang.Object this$role = this.getRole();
        final java.lang.Object other$role = other.getRole();
        if (this$role == null ? other$role != null : !this$role.equals(other$role)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        final java.lang.Object this$lastLoginTime = this.getLastLoginTime();
        final java.lang.Object other$lastLoginTime = other.getLastLoginTime();
        if (this$lastLoginTime == null ? other$lastLoginTime != null : !this$lastLoginTime.equals(other$lastLoginTime)) return false;
        final java.lang.Object this$totalStudyHours = this.getTotalStudyHours();
        final java.lang.Object other$totalStudyHours = other.getTotalStudyHours();
        if (this$totalStudyHours == null ? other$totalStudyHours != null : !this$totalStudyHours.equals(other$totalStudyHours)) return false;
        final java.lang.Object this$courseCount = this.getCourseCount();
        final java.lang.Object other$courseCount = other.getCourseCount();
        if (this$courseCount == null ? other$courseCount != null : !this$courseCount.equals(other$courseCount)) return false;
        final java.lang.Object this$pathCount = this.getPathCount();
        final java.lang.Object other$pathCount = other.getPathCount();
        if (this$pathCount == null ? other$pathCount != null : !this$pathCount.equals(other$pathCount)) return false;
        final java.lang.Object this$chatCount = this.getChatCount();
        final java.lang.Object other$chatCount = other.getChatCount();
        if (this$chatCount == null ? other$chatCount != null : !this$chatCount.equals(other$chatCount)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof UserProfileDTO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $username = this.getUsername();
        result = result * PRIME + ($username == null ? 43 : $username.hashCode());
        final java.lang.Object $nickname = this.getNickname();
        result = result * PRIME + ($nickname == null ? 43 : $nickname.hashCode());
        final java.lang.Object $email = this.getEmail();
        result = result * PRIME + ($email == null ? 43 : $email.hashCode());
        final java.lang.Object $phone = this.getPhone();
        result = result * PRIME + ($phone == null ? 43 : $phone.hashCode());
        final java.lang.Object $avatar = this.getAvatar();
        result = result * PRIME + ($avatar == null ? 43 : $avatar.hashCode());
        final java.lang.Object $role = this.getRole();
        result = result * PRIME + ($role == null ? 43 : $role.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        final java.lang.Object $lastLoginTime = this.getLastLoginTime();
        result = result * PRIME + ($lastLoginTime == null ? 43 : $lastLoginTime.hashCode());
        final java.lang.Object $totalStudyHours = this.getTotalStudyHours();
        result = result * PRIME + ($totalStudyHours == null ? 43 : $totalStudyHours.hashCode());
        final java.lang.Object $courseCount = this.getCourseCount();
        result = result * PRIME + ($courseCount == null ? 43 : $courseCount.hashCode());
        final java.lang.Object $pathCount = this.getPathCount();
        result = result * PRIME + ($pathCount == null ? 43 : $pathCount.hashCode());
        final java.lang.Object $chatCount = this.getChatCount();
        result = result * PRIME + ($chatCount == null ? 43 : $chatCount.hashCode());
        return result;
    }
}
