// Generated by delombok at Wed Jun 17 17:25:54 CST 2026
package com.edu.agent.module.course.dto;

public class CourseQueryDTO {
    private String category;
    private String difficulty;
    private String keyword;
    private Integer page = 1;
    private Integer size = 10;
    private Long teacherId;

    @java.lang.SuppressWarnings("all")
    public CourseQueryDTO() {
    }

    @java.lang.SuppressWarnings("all")
    public String getCategory() {
        return this.category;
    }

    @java.lang.SuppressWarnings("all")
    public String getDifficulty() {
        return this.difficulty;
    }

    @java.lang.SuppressWarnings("all")
    public String getKeyword() {
        return this.keyword;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getPage() {
        return this.page;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getSize() {
        return this.size;
    }

    @java.lang.SuppressWarnings("all")
    public Long getTeacherId() {
        return this.teacherId;
    }

    @java.lang.SuppressWarnings("all")
    public void setCategory(final String category) {
        this.category = category;
    }

    @java.lang.SuppressWarnings("all")
    public void setDifficulty(final String difficulty) {
        this.difficulty = difficulty;
    }

    @java.lang.SuppressWarnings("all")
    public void setKeyword(final String keyword) {
        this.keyword = keyword;
    }

    @java.lang.SuppressWarnings("all")
    public void setPage(final Integer page) {
        this.page = page;
    }

    @java.lang.SuppressWarnings("all")
    public void setSize(final Integer size) {
        this.size = size;
    }

    @java.lang.SuppressWarnings("all")
    public void setTeacherId(final Long teacherId) {
        this.teacherId = teacherId;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof CourseQueryDTO)) return false;
        final CourseQueryDTO other = (CourseQueryDTO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$page = this.getPage();
        final java.lang.Object other$page = other.getPage();
        if (this$page == null ? other$page != null : !this$page.equals(other$page)) return false;
        final java.lang.Object this$size = this.getSize();
        final java.lang.Object other$size = other.getSize();
        if (this$size == null ? other$size != null : !this$size.equals(other$size)) return false;
        final java.lang.Object this$teacherId = this.getTeacherId();
        final java.lang.Object other$teacherId = other.getTeacherId();
        if (this$teacherId == null ? other$teacherId != null : !this$teacherId.equals(other$teacherId)) return false;
        final java.lang.Object this$category = this.getCategory();
        final java.lang.Object other$category = other.getCategory();
        if (this$category == null ? other$category != null : !this$category.equals(other$category)) return false;
        final java.lang.Object this$difficulty = this.getDifficulty();
        final java.lang.Object other$difficulty = other.getDifficulty();
        if (this$difficulty == null ? other$difficulty != null : !this$difficulty.equals(other$difficulty)) return false;
        final java.lang.Object this$keyword = this.getKeyword();
        final java.lang.Object other$keyword = other.getKeyword();
        if (this$keyword == null ? other$keyword != null : !this$keyword.equals(other$keyword)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof CourseQueryDTO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $page = this.getPage();
        result = result * PRIME + ($page == null ? 43 : $page.hashCode());
        final java.lang.Object $size = this.getSize();
        result = result * PRIME + ($size == null ? 43 : $size.hashCode());
        final java.lang.Object $teacherId = this.getTeacherId();
        result = result * PRIME + ($teacherId == null ? 43 : $teacherId.hashCode());
        final java.lang.Object $category = this.getCategory();
        result = result * PRIME + ($category == null ? 43 : $category.hashCode());
        final java.lang.Object $difficulty = this.getDifficulty();
        result = result * PRIME + ($difficulty == null ? 43 : $difficulty.hashCode());
        final java.lang.Object $keyword = this.getKeyword();
        result = result * PRIME + ($keyword == null ? 43 : $keyword.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "CourseQueryDTO(category=" + this.getCategory() + ", difficulty=" + this.getDifficulty() + ", keyword=" + this.getKeyword() + ", page=" + this.getPage() + ", size=" + this.getSize() + ", teacherId=" + this.getTeacherId() + ")";
    }
}
