// Generated by delombok at Wed Jun 17 17:25:54 CST 2026
package com.edu.agent.module.chat.entity;

import com.edu.agent.common.base.BaseEntity;
import com.baomidou.mybatisplus.annotation.TableName;

@TableName("chat_message")
public class ChatMessage extends BaseEntity {
    private Long sessionId;
    private String role; // USER / ASSISTANT / SYSTEM
    private String content;
    private Integer tokenCount;

    @java.lang.SuppressWarnings("all")
    public ChatMessage() {
    }

    @java.lang.SuppressWarnings("all")
    public Long getSessionId() {
        return this.sessionId;
    }

    @java.lang.SuppressWarnings("all")
    public String getRole() {
        return this.role;
    }

    @java.lang.SuppressWarnings("all")
    public String getContent() {
        return this.content;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getTokenCount() {
        return this.tokenCount;
    }

    @java.lang.SuppressWarnings("all")
    public void setSessionId(final Long sessionId) {
        this.sessionId = sessionId;
    }

    @java.lang.SuppressWarnings("all")
    public void setRole(final String role) {
        this.role = role;
    }

    @java.lang.SuppressWarnings("all")
    public void setContent(final String content) {
        this.content = content;
    }

    @java.lang.SuppressWarnings("all")
    public void setTokenCount(final Integer tokenCount) {
        this.tokenCount = tokenCount;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "ChatMessage(sessionId=" + this.getSessionId() + ", role=" + this.getRole() + ", content=" + this.getContent() + ", tokenCount=" + this.getTokenCount() + ")";
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof ChatMessage)) return false;
        final ChatMessage other = (ChatMessage) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (!super.equals(o)) return false;
        final java.lang.Object this$sessionId = this.getSessionId();
        final java.lang.Object other$sessionId = other.getSessionId();
        if (this$sessionId == null ? other$sessionId != null : !this$sessionId.equals(other$sessionId)) return false;
        final java.lang.Object this$tokenCount = this.getTokenCount();
        final java.lang.Object other$tokenCount = other.getTokenCount();
        if (this$tokenCount == null ? other$tokenCount != null : !this$tokenCount.equals(other$tokenCount)) return false;
        final java.lang.Object this$role = this.getRole();
        final java.lang.Object other$role = other.getRole();
        if (this$role == null ? other$role != null : !this$role.equals(other$role)) return false;
        final java.lang.Object this$content = this.getContent();
        final java.lang.Object other$content = other.getContent();
        if (this$content == null ? other$content != null : !this$content.equals(other$content)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof ChatMessage;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = super.hashCode();
        final java.lang.Object $sessionId = this.getSessionId();
        result = result * PRIME + ($sessionId == null ? 43 : $sessionId.hashCode());
        final java.lang.Object $tokenCount = this.getTokenCount();
        result = result * PRIME + ($tokenCount == null ? 43 : $tokenCount.hashCode());
        final java.lang.Object $role = this.getRole();
        result = result * PRIME + ($role == null ? 43 : $role.hashCode());
        final java.lang.Object $content = this.getContent();
        result = result * PRIME + ($content == null ? 43 : $content.hashCode());
        return result;
    }
}
