// Generated by delombok at Wed Jun 17 17:25:54 CST 2026
package com.edu.agent.module.knowledge.dto;

import java.util.List;

public class BatchApproveDTO {
    private List<Long> ids;
    private boolean approved;
    private String remark;

    @java.lang.SuppressWarnings("all")
    public BatchApproveDTO() {
    }

    @java.lang.SuppressWarnings("all")
    public List<Long> getIds() {
        return this.ids;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isApproved() {
        return this.approved;
    }

    @java.lang.SuppressWarnings("all")
    public String getRemark() {
        return this.remark;
    }

    @java.lang.SuppressWarnings("all")
    public void setIds(final List<Long> ids) {
        this.ids = ids;
    }

    @java.lang.SuppressWarnings("all")
    public void setApproved(final boolean approved) {
        this.approved = approved;
    }

    @java.lang.SuppressWarnings("all")
    public void setRemark(final String remark) {
        this.remark = remark;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof BatchApproveDTO)) return false;
        final BatchApproveDTO other = (BatchApproveDTO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.isApproved() != other.isApproved()) return false;
        final java.lang.Object this$ids = this.getIds();
        final java.lang.Object other$ids = other.getIds();
        if (this$ids == null ? other$ids != null : !this$ids.equals(other$ids)) return false;
        final java.lang.Object this$remark = this.getRemark();
        final java.lang.Object other$remark = other.getRemark();
        if (this$remark == null ? other$remark != null : !this$remark.equals(other$remark)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof BatchApproveDTO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + (this.isApproved() ? 79 : 97);
        final java.lang.Object $ids = this.getIds();
        result = result * PRIME + ($ids == null ? 43 : $ids.hashCode());
        final java.lang.Object $remark = this.getRemark();
        result = result * PRIME + ($remark == null ? 43 : $remark.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "BatchApproveDTO(ids=" + this.getIds() + ", approved=" + this.isApproved() + ", remark=" + this.getRemark() + ")";
    }
}
