// Generated by delombok at Wed Jun 17 17:25:54 CST 2026
package com.edu.agent.module.knowledge.dto;

public class KnowledgeUploadDTO {
    private Long courseId;
    private String name;
    private String description;

    @java.lang.SuppressWarnings("all")
    public KnowledgeUploadDTO() {
    }

    @java.lang.SuppressWarnings("all")
    public Long getCourseId() {
        return this.courseId;
    }

    @java.lang.SuppressWarnings("all")
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    public String getDescription() {
        return this.description;
    }

    @java.lang.SuppressWarnings("all")
    public void setCourseId(final Long courseId) {
        this.courseId = courseId;
    }

    @java.lang.SuppressWarnings("all")
    public void setName(final String name) {
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    public void setDescription(final String description) {
        this.description = description;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof KnowledgeUploadDTO)) return false;
        final KnowledgeUploadDTO other = (KnowledgeUploadDTO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$courseId = this.getCourseId();
        final java.lang.Object other$courseId = other.getCourseId();
        if (this$courseId == null ? other$courseId != null : !this$courseId.equals(other$courseId)) return false;
        final java.lang.Object this$name = this.getName();
        final java.lang.Object other$name = other.getName();
        if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
        final java.lang.Object this$description = this.getDescription();
        final java.lang.Object other$description = other.getDescription();
        if (this$description == null ? other$description != null : !this$description.equals(other$description)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof KnowledgeUploadDTO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $courseId = this.getCourseId();
        result = result * PRIME + ($courseId == null ? 43 : $courseId.hashCode());
        final java.lang.Object $name = this.getName();
        result = result * PRIME + ($name == null ? 43 : $name.hashCode());
        final java.lang.Object $description = this.getDescription();
        result = result * PRIME + ($description == null ? 43 : $description.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "KnowledgeUploadDTO(courseId=" + this.getCourseId() + ", name=" + this.getName() + ", description=" + this.getDescription() + ")";
    }
    // Note: file is handled via MultipartFile in controller, not in this DTO
}
