// Generated by delombok at Wed Jun 17 17:25:54 CST 2026
package com.edu.agent.module.chat.dto;

/**
 * Typed response from Python Agent /agent/chat and /agent/chat/context endpoints.
 */
public class AgentChatResponse {
    private String response;
    private String sessionId;
    private String status;

    @java.lang.SuppressWarnings("all")
    public AgentChatResponse() {
    }

    @java.lang.SuppressWarnings("all")
    public String getResponse() {
        return this.response;
    }

    @java.lang.SuppressWarnings("all")
    public String getSessionId() {
        return this.sessionId;
    }

    @java.lang.SuppressWarnings("all")
    public String getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    public void setResponse(final String response) {
        this.response = response;
    }

    @java.lang.SuppressWarnings("all")
    public void setSessionId(final String sessionId) {
        this.sessionId = sessionId;
    }

    @java.lang.SuppressWarnings("all")
    public void setStatus(final String status) {
        this.status = status;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof AgentChatResponse)) return false;
        final AgentChatResponse other = (AgentChatResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$response = this.getResponse();
        final java.lang.Object other$response = other.getResponse();
        if (this$response == null ? other$response != null : !this$response.equals(other$response)) return false;
        final java.lang.Object this$sessionId = this.getSessionId();
        final java.lang.Object other$sessionId = other.getSessionId();
        if (this$sessionId == null ? other$sessionId != null : !this$sessionId.equals(other$sessionId)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof AgentChatResponse;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $response = this.getResponse();
        result = result * PRIME + ($response == null ? 43 : $response.hashCode());
        final java.lang.Object $sessionId = this.getSessionId();
        result = result * PRIME + ($sessionId == null ? 43 : $sessionId.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "AgentChatResponse(response=" + this.getResponse() + ", sessionId=" + this.getSessionId() + ", status=" + this.getStatus() + ")";
    }
}
