// Generated by delombok at Wed Jun 17 17:25:54 CST 2026
package com.edu.agent.module.chat.dto;

/**
 * Typed response from Python Agent /agent/knowledge/ingest endpoint.
 */
public class AgentIngestResponse {
    private Long knowledgeId;
    private Integer chunks;
    private String status;

    @java.lang.SuppressWarnings("all")
    public AgentIngestResponse() {
    }

    @java.lang.SuppressWarnings("all")
    public Long getKnowledgeId() {
        return this.knowledgeId;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getChunks() {
        return this.chunks;
    }

    @java.lang.SuppressWarnings("all")
    public String getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    public void setKnowledgeId(final Long knowledgeId) {
        this.knowledgeId = knowledgeId;
    }

    @java.lang.SuppressWarnings("all")
    public void setChunks(final Integer chunks) {
        this.chunks = chunks;
    }

    @java.lang.SuppressWarnings("all")
    public void setStatus(final String status) {
        this.status = status;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof AgentIngestResponse)) return false;
        final AgentIngestResponse other = (AgentIngestResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$knowledgeId = this.getKnowledgeId();
        final java.lang.Object other$knowledgeId = other.getKnowledgeId();
        if (this$knowledgeId == null ? other$knowledgeId != null : !this$knowledgeId.equals(other$knowledgeId)) return false;
        final java.lang.Object this$chunks = this.getChunks();
        final java.lang.Object other$chunks = other.getChunks();
        if (this$chunks == null ? other$chunks != null : !this$chunks.equals(other$chunks)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof AgentIngestResponse;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $knowledgeId = this.getKnowledgeId();
        result = result * PRIME + ($knowledgeId == null ? 43 : $knowledgeId.hashCode());
        final java.lang.Object $chunks = this.getChunks();
        result = result * PRIME + ($chunks == null ? 43 : $chunks.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "AgentIngestResponse(knowledgeId=" + this.getKnowledgeId() + ", chunks=" + this.getChunks() + ", status=" + this.getStatus() + ")";
    }
}
