// Generated by delombok at Wed Jun 17 17:25:54 CST 2026
package com.edu.agent.module.chat.dto;

import java.time.LocalDateTime;

public class ChatSessionDTO {
    private Long id;
    private Long courseId;
    private String courseName;
    private String title;
    private String lastMessage;
    private LocalDateTime lastMessageTime;
    private LocalDateTime createTime;

    @java.lang.SuppressWarnings("all")
    public ChatSessionDTO() {
    }

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public Long getCourseId() {
        return this.courseId;
    }

    @java.lang.SuppressWarnings("all")
    public String getCourseName() {
        return this.courseName;
    }

    @java.lang.SuppressWarnings("all")
    public String getTitle() {
        return this.title;
    }

    @java.lang.SuppressWarnings("all")
    public String getLastMessage() {
        return this.lastMessage;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getLastMessageTime() {
        return this.lastMessageTime;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setCourseId(final Long courseId) {
        this.courseId = courseId;
    }

    @java.lang.SuppressWarnings("all")
    public void setCourseName(final String courseName) {
        this.courseName = courseName;
    }

    @java.lang.SuppressWarnings("all")
    public void setTitle(final String title) {
        this.title = title;
    }

    @java.lang.SuppressWarnings("all")
    public void setLastMessage(final String lastMessage) {
        this.lastMessage = lastMessage;
    }

    @java.lang.SuppressWarnings("all")
    public void setLastMessageTime(final LocalDateTime lastMessageTime) {
        this.lastMessageTime = lastMessageTime;
    }

    @java.lang.SuppressWarnings("all")
    public void setCreateTime(final LocalDateTime createTime) {
        this.createTime = createTime;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof ChatSessionDTO)) return false;
        final ChatSessionDTO other = (ChatSessionDTO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$courseId = this.getCourseId();
        final java.lang.Object other$courseId = other.getCourseId();
        if (this$courseId == null ? other$courseId != null : !this$courseId.equals(other$courseId)) return false;
        final java.lang.Object this$courseName = this.getCourseName();
        final java.lang.Object other$courseName = other.getCourseName();
        if (this$courseName == null ? other$courseName != null : !this$courseName.equals(other$courseName)) return false;
        final java.lang.Object this$title = this.getTitle();
        final java.lang.Object other$title = other.getTitle();
        if (this$title == null ? other$title != null : !this$title.equals(other$title)) return false;
        final java.lang.Object this$lastMessage = this.getLastMessage();
        final java.lang.Object other$lastMessage = other.getLastMessage();
        if (this$lastMessage == null ? other$lastMessage != null : !this$lastMessage.equals(other$lastMessage)) return false;
        final java.lang.Object this$lastMessageTime = this.getLastMessageTime();
        final java.lang.Object other$lastMessageTime = other.getLastMessageTime();
        if (this$lastMessageTime == null ? other$lastMessageTime != null : !this$lastMessageTime.equals(other$lastMessageTime)) return false;
        final java.lang.Object this$createTime = this.getCreateTime();
        final java.lang.Object other$createTime = other.getCreateTime();
        if (this$createTime == null ? other$createTime != null : !this$createTime.equals(other$createTime)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof ChatSessionDTO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $courseId = this.getCourseId();
        result = result * PRIME + ($courseId == null ? 43 : $courseId.hashCode());
        final java.lang.Object $courseName = this.getCourseName();
        result = result * PRIME + ($courseName == null ? 43 : $courseName.hashCode());
        final java.lang.Object $title = this.getTitle();
        result = result * PRIME + ($title == null ? 43 : $title.hashCode());
        final java.lang.Object $lastMessage = this.getLastMessage();
        result = result * PRIME + ($lastMessage == null ? 43 : $lastMessage.hashCode());
        final java.lang.Object $lastMessageTime = this.getLastMessageTime();
        result = result * PRIME + ($lastMessageTime == null ? 43 : $lastMessageTime.hashCode());
        final java.lang.Object $createTime = this.getCreateTime();
        result = result * PRIME + ($createTime == null ? 43 : $createTime.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "ChatSessionDTO(id=" + this.getId() + ", courseId=" + this.getCourseId() + ", courseName=" + this.getCourseName() + ", title=" + this.getTitle() + ", lastMessage=" + this.getLastMessage() + ", lastMessageTime=" + this.getLastMessageTime() + ", createTime=" + this.getCreateTime() + ")";
    }
}
