// Generated by delombok at Wed Jun 17 17:25:54 CST 2026
package com.edu.agent.module.chat.dto;

public class ChatResponse {
    private String response;
    private Long sessionId;
    private Long messageId;
    private String agentId;

    @java.lang.SuppressWarnings("all")
    public ChatResponse() {
    }

    @java.lang.SuppressWarnings("all")
    public String getResponse() {
        return this.response;
    }

    @java.lang.SuppressWarnings("all")
    public Long getSessionId() {
        return this.sessionId;
    }

    @java.lang.SuppressWarnings("all")
    public Long getMessageId() {
        return this.messageId;
    }

    @java.lang.SuppressWarnings("all")
    public String getAgentId() {
        return this.agentId;
    }

    @java.lang.SuppressWarnings("all")
    public void setResponse(final String response) {
        this.response = response;
    }

    @java.lang.SuppressWarnings("all")
    public void setSessionId(final Long sessionId) {
        this.sessionId = sessionId;
    }

    @java.lang.SuppressWarnings("all")
    public void setMessageId(final Long messageId) {
        this.messageId = messageId;
    }

    @java.lang.SuppressWarnings("all")
    public void setAgentId(final String agentId) {
        this.agentId = agentId;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof ChatResponse)) return false;
        final ChatResponse other = (ChatResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$sessionId = this.getSessionId();
        final java.lang.Object other$sessionId = other.getSessionId();
        if (this$sessionId == null ? other$sessionId != null : !this$sessionId.equals(other$sessionId)) return false;
        final java.lang.Object this$messageId = this.getMessageId();
        final java.lang.Object other$messageId = other.getMessageId();
        if (this$messageId == null ? other$messageId != null : !this$messageId.equals(other$messageId)) return false;
        final java.lang.Object this$response = this.getResponse();
        final java.lang.Object other$response = other.getResponse();
        if (this$response == null ? other$response != null : !this$response.equals(other$response)) return false;
        final java.lang.Object this$agentId = this.getAgentId();
        final java.lang.Object other$agentId = other.getAgentId();
        if (this$agentId == null ? other$agentId != null : !this$agentId.equals(other$agentId)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof ChatResponse;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $sessionId = this.getSessionId();
        result = result * PRIME + ($sessionId == null ? 43 : $sessionId.hashCode());
        final java.lang.Object $messageId = this.getMessageId();
        result = result * PRIME + ($messageId == null ? 43 : $messageId.hashCode());
        final java.lang.Object $response = this.getResponse();
        result = result * PRIME + ($response == null ? 43 : $response.hashCode());
        final java.lang.Object $agentId = this.getAgentId();
        result = result * PRIME + ($agentId == null ? 43 : $agentId.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "ChatResponse(response=" + this.getResponse() + ", sessionId=" + this.getSessionId() + ", messageId=" + this.getMessageId() + ", agentId=" + this.getAgentId() + ")";
    }
}
