// Generated by delombok at Wed Jun 17 17:25:54 CST 2026
package com.edu.agent.module.schedule.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotEmpty;
import java.util.List;

public class SaveConfigRequest {
    @NotBlank(message = "开学日期不能为空")
    private String semesterStartDate;
    @NotEmpty(message = "时间段配置不能为空")
    private List<ScheduleConfigDTO.PeriodConfig> periodConfig;

    @java.lang.SuppressWarnings("all")
    public SaveConfigRequest() {
    }

    @java.lang.SuppressWarnings("all")
    public String getSemesterStartDate() {
        return this.semesterStartDate;
    }

    @java.lang.SuppressWarnings("all")
    public List<ScheduleConfigDTO.PeriodConfig> getPeriodConfig() {
        return this.periodConfig;
    }

    @java.lang.SuppressWarnings("all")
    public void setSemesterStartDate(final String semesterStartDate) {
        this.semesterStartDate = semesterStartDate;
    }

    @java.lang.SuppressWarnings("all")
    public void setPeriodConfig(final List<ScheduleConfigDTO.PeriodConfig> periodConfig) {
        this.periodConfig = periodConfig;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof SaveConfigRequest)) return false;
        final SaveConfigRequest other = (SaveConfigRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$semesterStartDate = this.getSemesterStartDate();
        final java.lang.Object other$semesterStartDate = other.getSemesterStartDate();
        if (this$semesterStartDate == null ? other$semesterStartDate != null : !this$semesterStartDate.equals(other$semesterStartDate)) return false;
        final java.lang.Object this$periodConfig = this.getPeriodConfig();
        final java.lang.Object other$periodConfig = other.getPeriodConfig();
        if (this$periodConfig == null ? other$periodConfig != null : !this$periodConfig.equals(other$periodConfig)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof SaveConfigRequest;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $semesterStartDate = this.getSemesterStartDate();
        result = result * PRIME + ($semesterStartDate == null ? 43 : $semesterStartDate.hashCode());
        final java.lang.Object $periodConfig = this.getPeriodConfig();
        result = result * PRIME + ($periodConfig == null ? 43 : $periodConfig.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "SaveConfigRequest(semesterStartDate=" + this.getSemesterStartDate() + ", periodConfig=" + this.getPeriodConfig() + ")";
    }
}
