// Generated by delombok at Wed Jun 17 17:25:54 CST 2026
package com.edu.agent.module.schedule.dto;

import java.time.LocalDate;
import java.util.List;

public class ScheduleConfigDTO {
    private Long id;
    private LocalDate semesterStartDate;
    private List<PeriodConfig> periodConfig;


    public static class PeriodConfig {
        private String name;
        private String startTime; // HH:mm
        private String endTime; // HH:mm

        @java.lang.SuppressWarnings("all")
        public String getName() {
            return this.name;
        }

        @java.lang.SuppressWarnings("all")
        public String getStartTime() {
            return this.startTime;
        }

        @java.lang.SuppressWarnings("all")
        public String getEndTime() {
            return this.endTime;
        }

        @java.lang.SuppressWarnings("all")
        public void setName(final String name) {
            this.name = name;
        }

        @java.lang.SuppressWarnings("all")
        public void setStartTime(final String startTime) {
            this.startTime = startTime;
        }

        @java.lang.SuppressWarnings("all")
        public void setEndTime(final String endTime) {
            this.endTime = endTime;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof ScheduleConfigDTO.PeriodConfig)) return false;
            final ScheduleConfigDTO.PeriodConfig other = (ScheduleConfigDTO.PeriodConfig) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            final java.lang.Object this$name = this.getName();
            final java.lang.Object other$name = other.getName();
            if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
            final java.lang.Object this$startTime = this.getStartTime();
            final java.lang.Object other$startTime = other.getStartTime();
            if (this$startTime == null ? other$startTime != null : !this$startTime.equals(other$startTime)) return false;
            final java.lang.Object this$endTime = this.getEndTime();
            final java.lang.Object other$endTime = other.getEndTime();
            if (this$endTime == null ? other$endTime != null : !this$endTime.equals(other$endTime)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof ScheduleConfigDTO.PeriodConfig;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            final java.lang.Object $name = this.getName();
            result = result * PRIME + ($name == null ? 43 : $name.hashCode());
            final java.lang.Object $startTime = this.getStartTime();
            result = result * PRIME + ($startTime == null ? 43 : $startTime.hashCode());
            final java.lang.Object $endTime = this.getEndTime();
            result = result * PRIME + ($endTime == null ? 43 : $endTime.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "ScheduleConfigDTO.PeriodConfig(name=" + this.getName() + ", startTime=" + this.getStartTime() + ", endTime=" + this.getEndTime() + ")";
        }

        @java.lang.SuppressWarnings("all")
        public PeriodConfig() {
        }

        @java.lang.SuppressWarnings("all")
        public PeriodConfig(final String name, final String startTime, final String endTime) {
            this.name = name;
            this.startTime = startTime;
            this.endTime = endTime;
        }
    }

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDate getSemesterStartDate() {
        return this.semesterStartDate;
    }

    @java.lang.SuppressWarnings("all")
    public List<PeriodConfig> getPeriodConfig() {
        return this.periodConfig;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setSemesterStartDate(final LocalDate semesterStartDate) {
        this.semesterStartDate = semesterStartDate;
    }

    @java.lang.SuppressWarnings("all")
    public void setPeriodConfig(final List<PeriodConfig> periodConfig) {
        this.periodConfig = periodConfig;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof ScheduleConfigDTO)) return false;
        final ScheduleConfigDTO other = (ScheduleConfigDTO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$semesterStartDate = this.getSemesterStartDate();
        final java.lang.Object other$semesterStartDate = other.getSemesterStartDate();
        if (this$semesterStartDate == null ? other$semesterStartDate != null : !this$semesterStartDate.equals(other$semesterStartDate)) return false;
        final java.lang.Object this$periodConfig = this.getPeriodConfig();
        final java.lang.Object other$periodConfig = other.getPeriodConfig();
        if (this$periodConfig == null ? other$periodConfig != null : !this$periodConfig.equals(other$periodConfig)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof ScheduleConfigDTO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $semesterStartDate = this.getSemesterStartDate();
        result = result * PRIME + ($semesterStartDate == null ? 43 : $semesterStartDate.hashCode());
        final java.lang.Object $periodConfig = this.getPeriodConfig();
        result = result * PRIME + ($periodConfig == null ? 43 : $periodConfig.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "ScheduleConfigDTO(id=" + this.getId() + ", semesterStartDate=" + this.getSemesterStartDate() + ", periodConfig=" + this.getPeriodConfig() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public ScheduleConfigDTO() {
    }

    @java.lang.SuppressWarnings("all")
    public ScheduleConfigDTO(final Long id, final LocalDate semesterStartDate, final List<PeriodConfig> periodConfig) {
        this.id = id;
        this.semesterStartDate = semesterStartDate;
        this.periodConfig = periodConfig;
    }
}
