// Generated by delombok at Wed Jun 17 17:25:54 CST 2026
package com.edu.agent.module.schedule.dto;

import java.time.LocalDate;
import java.util.List;

public class ScheduleWeekViewDTO {
    private Integer weekNumber;
    private LocalDate weekStartDate;
    private LocalDate weekEndDate;
    private List<DaySchedule> days;


    public static class DaySchedule {
        private Integer dayOfWeek; // 1=周一, 7=周日
        private LocalDate date; // 实际日期
        private String dayLabel; // 周几 或 "非本周"
        private List<PeriodSlot> periods;

        @java.lang.SuppressWarnings("all")
        public DaySchedule() {
        }

        @java.lang.SuppressWarnings("all")
        public Integer getDayOfWeek() {
            return this.dayOfWeek;
        }

        @java.lang.SuppressWarnings("all")
        public LocalDate getDate() {
            return this.date;
        }

        @java.lang.SuppressWarnings("all")
        public String getDayLabel() {
            return this.dayLabel;
        }

        @java.lang.SuppressWarnings("all")
        public List<PeriodSlot> getPeriods() {
            return this.periods;
        }

        @java.lang.SuppressWarnings("all")
        public void setDayOfWeek(final Integer dayOfWeek) {
            this.dayOfWeek = dayOfWeek;
        }

        @java.lang.SuppressWarnings("all")
        public void setDate(final LocalDate date) {
            this.date = date;
        }

        @java.lang.SuppressWarnings("all")
        public void setDayLabel(final String dayLabel) {
            this.dayLabel = dayLabel;
        }

        @java.lang.SuppressWarnings("all")
        public void setPeriods(final List<PeriodSlot> periods) {
            this.periods = periods;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof ScheduleWeekViewDTO.DaySchedule)) return false;
            final ScheduleWeekViewDTO.DaySchedule other = (ScheduleWeekViewDTO.DaySchedule) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            final java.lang.Object this$dayOfWeek = this.getDayOfWeek();
            final java.lang.Object other$dayOfWeek = other.getDayOfWeek();
            if (this$dayOfWeek == null ? other$dayOfWeek != null : !this$dayOfWeek.equals(other$dayOfWeek)) return false;
            final java.lang.Object this$date = this.getDate();
            final java.lang.Object other$date = other.getDate();
            if (this$date == null ? other$date != null : !this$date.equals(other$date)) return false;
            final java.lang.Object this$dayLabel = this.getDayLabel();
            final java.lang.Object other$dayLabel = other.getDayLabel();
            if (this$dayLabel == null ? other$dayLabel != null : !this$dayLabel.equals(other$dayLabel)) return false;
            final java.lang.Object this$periods = this.getPeriods();
            final java.lang.Object other$periods = other.getPeriods();
            if (this$periods == null ? other$periods != null : !this$periods.equals(other$periods)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof ScheduleWeekViewDTO.DaySchedule;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            final java.lang.Object $dayOfWeek = this.getDayOfWeek();
            result = result * PRIME + ($dayOfWeek == null ? 43 : $dayOfWeek.hashCode());
            final java.lang.Object $date = this.getDate();
            result = result * PRIME + ($date == null ? 43 : $date.hashCode());
            final java.lang.Object $dayLabel = this.getDayLabel();
            result = result * PRIME + ($dayLabel == null ? 43 : $dayLabel.hashCode());
            final java.lang.Object $periods = this.getPeriods();
            result = result * PRIME + ($periods == null ? 43 : $periods.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "ScheduleWeekViewDTO.DaySchedule(dayOfWeek=" + this.getDayOfWeek() + ", date=" + this.getDate() + ", dayLabel=" + this.getDayLabel() + ", periods=" + this.getPeriods() + ")";
        }
    }


    public static class PeriodSlot {
        private Integer periodIndex;
        private String periodName;
        private String startTime;
        private String endTime;
        private String courseName; // null表示空闲

        @java.lang.SuppressWarnings("all")
        public PeriodSlot() {
        }

        @java.lang.SuppressWarnings("all")
        public Integer getPeriodIndex() {
            return this.periodIndex;
        }

        @java.lang.SuppressWarnings("all")
        public String getPeriodName() {
            return this.periodName;
        }

        @java.lang.SuppressWarnings("all")
        public String getStartTime() {
            return this.startTime;
        }

        @java.lang.SuppressWarnings("all")
        public String getEndTime() {
            return this.endTime;
        }

        @java.lang.SuppressWarnings("all")
        public String getCourseName() {
            return this.courseName;
        }

        @java.lang.SuppressWarnings("all")
        public void setPeriodIndex(final Integer periodIndex) {
            this.periodIndex = periodIndex;
        }

        @java.lang.SuppressWarnings("all")
        public void setPeriodName(final String periodName) {
            this.periodName = periodName;
        }

        @java.lang.SuppressWarnings("all")
        public void setStartTime(final String startTime) {
            this.startTime = startTime;
        }

        @java.lang.SuppressWarnings("all")
        public void setEndTime(final String endTime) {
            this.endTime = endTime;
        }

        @java.lang.SuppressWarnings("all")
        public void setCourseName(final String courseName) {
            this.courseName = courseName;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof ScheduleWeekViewDTO.PeriodSlot)) return false;
            final ScheduleWeekViewDTO.PeriodSlot other = (ScheduleWeekViewDTO.PeriodSlot) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            final java.lang.Object this$periodIndex = this.getPeriodIndex();
            final java.lang.Object other$periodIndex = other.getPeriodIndex();
            if (this$periodIndex == null ? other$periodIndex != null : !this$periodIndex.equals(other$periodIndex)) return false;
            final java.lang.Object this$periodName = this.getPeriodName();
            final java.lang.Object other$periodName = other.getPeriodName();
            if (this$periodName == null ? other$periodName != null : !this$periodName.equals(other$periodName)) return false;
            final java.lang.Object this$startTime = this.getStartTime();
            final java.lang.Object other$startTime = other.getStartTime();
            if (this$startTime == null ? other$startTime != null : !this$startTime.equals(other$startTime)) return false;
            final java.lang.Object this$endTime = this.getEndTime();
            final java.lang.Object other$endTime = other.getEndTime();
            if (this$endTime == null ? other$endTime != null : !this$endTime.equals(other$endTime)) return false;
            final java.lang.Object this$courseName = this.getCourseName();
            final java.lang.Object other$courseName = other.getCourseName();
            if (this$courseName == null ? other$courseName != null : !this$courseName.equals(other$courseName)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof ScheduleWeekViewDTO.PeriodSlot;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            final java.lang.Object $periodIndex = this.getPeriodIndex();
            result = result * PRIME + ($periodIndex == null ? 43 : $periodIndex.hashCode());
            final java.lang.Object $periodName = this.getPeriodName();
            result = result * PRIME + ($periodName == null ? 43 : $periodName.hashCode());
            final java.lang.Object $startTime = this.getStartTime();
            result = result * PRIME + ($startTime == null ? 43 : $startTime.hashCode());
            final java.lang.Object $endTime = this.getEndTime();
            result = result * PRIME + ($endTime == null ? 43 : $endTime.hashCode());
            final java.lang.Object $courseName = this.getCourseName();
            result = result * PRIME + ($courseName == null ? 43 : $courseName.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "ScheduleWeekViewDTO.PeriodSlot(periodIndex=" + this.getPeriodIndex() + ", periodName=" + this.getPeriodName() + ", startTime=" + this.getStartTime() + ", endTime=" + this.getEndTime() + ", courseName=" + this.getCourseName() + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public ScheduleWeekViewDTO() {
    }

    @java.lang.SuppressWarnings("all")
    public Integer getWeekNumber() {
        return this.weekNumber;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDate getWeekStartDate() {
        return this.weekStartDate;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDate getWeekEndDate() {
        return this.weekEndDate;
    }

    @java.lang.SuppressWarnings("all")
    public List<DaySchedule> getDays() {
        return this.days;
    }

    @java.lang.SuppressWarnings("all")
    public void setWeekNumber(final Integer weekNumber) {
        this.weekNumber = weekNumber;
    }

    @java.lang.SuppressWarnings("all")
    public void setWeekStartDate(final LocalDate weekStartDate) {
        this.weekStartDate = weekStartDate;
    }

    @java.lang.SuppressWarnings("all")
    public void setWeekEndDate(final LocalDate weekEndDate) {
        this.weekEndDate = weekEndDate;
    }

    @java.lang.SuppressWarnings("all")
    public void setDays(final List<DaySchedule> days) {
        this.days = days;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof ScheduleWeekViewDTO)) return false;
        final ScheduleWeekViewDTO other = (ScheduleWeekViewDTO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$weekNumber = this.getWeekNumber();
        final java.lang.Object other$weekNumber = other.getWeekNumber();
        if (this$weekNumber == null ? other$weekNumber != null : !this$weekNumber.equals(other$weekNumber)) return false;
        final java.lang.Object this$weekStartDate = this.getWeekStartDate();
        final java.lang.Object other$weekStartDate = other.getWeekStartDate();
        if (this$weekStartDate == null ? other$weekStartDate != null : !this$weekStartDate.equals(other$weekStartDate)) return false;
        final java.lang.Object this$weekEndDate = this.getWeekEndDate();
        final java.lang.Object other$weekEndDate = other.getWeekEndDate();
        if (this$weekEndDate == null ? other$weekEndDate != null : !this$weekEndDate.equals(other$weekEndDate)) return false;
        final java.lang.Object this$days = this.getDays();
        final java.lang.Object other$days = other.getDays();
        if (this$days == null ? other$days != null : !this$days.equals(other$days)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof ScheduleWeekViewDTO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $weekNumber = this.getWeekNumber();
        result = result * PRIME + ($weekNumber == null ? 43 : $weekNumber.hashCode());
        final java.lang.Object $weekStartDate = this.getWeekStartDate();
        result = result * PRIME + ($weekStartDate == null ? 43 : $weekStartDate.hashCode());
        final java.lang.Object $weekEndDate = this.getWeekEndDate();
        result = result * PRIME + ($weekEndDate == null ? 43 : $weekEndDate.hashCode());
        final java.lang.Object $days = this.getDays();
        result = result * PRIME + ($days == null ? 43 : $days.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "ScheduleWeekViewDTO(weekNumber=" + this.getWeekNumber() + ", weekStartDate=" + this.getWeekStartDate() + ", weekEndDate=" + this.getWeekEndDate() + ", days=" + this.getDays() + ")";
    }
}
