// Generated by delombok at Wed Jun 17 17:25:54 CST 2026
package com.edu.agent.module.schedule.dto;

import java.util.List;

public class ScheduleCourseDTO {
    private Long id;
    private String name;
    private List<Integer> weekNumbers;
    private List<Integer> dayOfWeeks;
    private List<Integer> periodIndexes;
    private String location;
    private String remark;

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    public List<Integer> getWeekNumbers() {
        return this.weekNumbers;
    }

    @java.lang.SuppressWarnings("all")
    public List<Integer> getDayOfWeeks() {
        return this.dayOfWeeks;
    }

    @java.lang.SuppressWarnings("all")
    public List<Integer> getPeriodIndexes() {
        return this.periodIndexes;
    }

    @java.lang.SuppressWarnings("all")
    public String getLocation() {
        return this.location;
    }

    @java.lang.SuppressWarnings("all")
    public String getRemark() {
        return this.remark;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setName(final String name) {
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    public void setWeekNumbers(final List<Integer> weekNumbers) {
        this.weekNumbers = weekNumbers;
    }

    @java.lang.SuppressWarnings("all")
    public void setDayOfWeeks(final List<Integer> dayOfWeeks) {
        this.dayOfWeeks = dayOfWeeks;
    }

    @java.lang.SuppressWarnings("all")
    public void setPeriodIndexes(final List<Integer> periodIndexes) {
        this.periodIndexes = periodIndexes;
    }

    @java.lang.SuppressWarnings("all")
    public void setLocation(final String location) {
        this.location = location;
    }

    @java.lang.SuppressWarnings("all")
    public void setRemark(final String remark) {
        this.remark = remark;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof ScheduleCourseDTO)) return false;
        final ScheduleCourseDTO other = (ScheduleCourseDTO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$name = this.getName();
        final java.lang.Object other$name = other.getName();
        if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
        final java.lang.Object this$weekNumbers = this.getWeekNumbers();
        final java.lang.Object other$weekNumbers = other.getWeekNumbers();
        if (this$weekNumbers == null ? other$weekNumbers != null : !this$weekNumbers.equals(other$weekNumbers)) return false;
        final java.lang.Object this$dayOfWeeks = this.getDayOfWeeks();
        final java.lang.Object other$dayOfWeeks = other.getDayOfWeeks();
        if (this$dayOfWeeks == null ? other$dayOfWeeks != null : !this$dayOfWeeks.equals(other$dayOfWeeks)) return false;
        final java.lang.Object this$periodIndexes = this.getPeriodIndexes();
        final java.lang.Object other$periodIndexes = other.getPeriodIndexes();
        if (this$periodIndexes == null ? other$periodIndexes != null : !this$periodIndexes.equals(other$periodIndexes)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof ScheduleCourseDTO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $name = this.getName();
        result = result * PRIME + ($name == null ? 43 : $name.hashCode());
        final java.lang.Object $weekNumbers = this.getWeekNumbers();
        result = result * PRIME + ($weekNumbers == null ? 43 : $weekNumbers.hashCode());
        final java.lang.Object $dayOfWeeks = this.getDayOfWeeks();
        result = result * PRIME + ($dayOfWeeks == null ? 43 : $dayOfWeeks.hashCode());
        final java.lang.Object $periodIndexes = this.getPeriodIndexes();
        result = result * PRIME + ($periodIndexes == null ? 43 : $periodIndexes.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "ScheduleCourseDTO(id=" + this.getId() + ", name=" + this.getName() + ", weekNumbers=" + this.getWeekNumbers() + ", dayOfWeeks=" + this.getDayOfWeeks() + ", periodIndexes=" + this.getPeriodIndexes() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public ScheduleCourseDTO() {
    }

    @java.lang.SuppressWarnings("all")
    public ScheduleCourseDTO(final Long id, final String name, final List<Integer> weekNumbers, final List<Integer> dayOfWeeks, final List<Integer> periodIndexes) {
        this.id = id;
        this.name = name;
        this.weekNumbers = weekNumbers;
        this.dayOfWeeks = dayOfWeeks;
        this.periodIndexes = periodIndexes;
    }
}
