// Generated by delombok at Wed Jun 17 17:25:54 CST 2026
package com.edu.agent.module.admin.dto;

public class DashboardStatsDTO {
    private Integer totalUsers;
    private Integer totalTeachers;
    private Integer totalStudents;
    private Integer totalCourses;
    private Long totalConversations;
    private Integer activeStudentsToday;
    private Integer totalKnowledgeItems;
    private Integer totalPaths;

    @java.lang.SuppressWarnings("all")
    public DashboardStatsDTO() {
    }

    @java.lang.SuppressWarnings("all")
    public Integer getTotalUsers() {
        return this.totalUsers;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getTotalTeachers() {
        return this.totalTeachers;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getTotalStudents() {
        return this.totalStudents;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getTotalCourses() {
        return this.totalCourses;
    }

    @java.lang.SuppressWarnings("all")
    public Long getTotalConversations() {
        return this.totalConversations;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getActiveStudentsToday() {
        return this.activeStudentsToday;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getTotalKnowledgeItems() {
        return this.totalKnowledgeItems;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getTotalPaths() {
        return this.totalPaths;
    }

    @java.lang.SuppressWarnings("all")
    public void setTotalUsers(final Integer totalUsers) {
        this.totalUsers = totalUsers;
    }

    @java.lang.SuppressWarnings("all")
    public void setTotalTeachers(final Integer totalTeachers) {
        this.totalTeachers = totalTeachers;
    }

    @java.lang.SuppressWarnings("all")
    public void setTotalStudents(final Integer totalStudents) {
        this.totalStudents = totalStudents;
    }

    @java.lang.SuppressWarnings("all")
    public void setTotalCourses(final Integer totalCourses) {
        this.totalCourses = totalCourses;
    }

    @java.lang.SuppressWarnings("all")
    public void setTotalConversations(final Long totalConversations) {
        this.totalConversations = totalConversations;
    }

    @java.lang.SuppressWarnings("all")
    public void setActiveStudentsToday(final Integer activeStudentsToday) {
        this.activeStudentsToday = activeStudentsToday;
    }

    @java.lang.SuppressWarnings("all")
    public void setTotalKnowledgeItems(final Integer totalKnowledgeItems) {
        this.totalKnowledgeItems = totalKnowledgeItems;
    }

    @java.lang.SuppressWarnings("all")
    public void setTotalPaths(final Integer totalPaths) {
        this.totalPaths = totalPaths;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof DashboardStatsDTO)) return false;
        final DashboardStatsDTO other = (DashboardStatsDTO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$totalUsers = this.getTotalUsers();
        final java.lang.Object other$totalUsers = other.getTotalUsers();
        if (this$totalUsers == null ? other$totalUsers != null : !this$totalUsers.equals(other$totalUsers)) return false;
        final java.lang.Object this$totalTeachers = this.getTotalTeachers();
        final java.lang.Object other$totalTeachers = other.getTotalTeachers();
        if (this$totalTeachers == null ? other$totalTeachers != null : !this$totalTeachers.equals(other$totalTeachers)) return false;
        final java.lang.Object this$totalStudents = this.getTotalStudents();
        final java.lang.Object other$totalStudents = other.getTotalStudents();
        if (this$totalStudents == null ? other$totalStudents != null : !this$totalStudents.equals(other$totalStudents)) return false;
        final java.lang.Object this$totalCourses = this.getTotalCourses();
        final java.lang.Object other$totalCourses = other.getTotalCourses();
        if (this$totalCourses == null ? other$totalCourses != null : !this$totalCourses.equals(other$totalCourses)) return false;
        final java.lang.Object this$totalConversations = this.getTotalConversations();
        final java.lang.Object other$totalConversations = other.getTotalConversations();
        if (this$totalConversations == null ? other$totalConversations != null : !this$totalConversations.equals(other$totalConversations)) return false;
        final java.lang.Object this$activeStudentsToday = this.getActiveStudentsToday();
        final java.lang.Object other$activeStudentsToday = other.getActiveStudentsToday();
        if (this$activeStudentsToday == null ? other$activeStudentsToday != null : !this$activeStudentsToday.equals(other$activeStudentsToday)) return false;
        final java.lang.Object this$totalKnowledgeItems = this.getTotalKnowledgeItems();
        final java.lang.Object other$totalKnowledgeItems = other.getTotalKnowledgeItems();
        if (this$totalKnowledgeItems == null ? other$totalKnowledgeItems != null : !this$totalKnowledgeItems.equals(other$totalKnowledgeItems)) return false;
        final java.lang.Object this$totalPaths = this.getTotalPaths();
        final java.lang.Object other$totalPaths = other.getTotalPaths();
        if (this$totalPaths == null ? other$totalPaths != null : !this$totalPaths.equals(other$totalPaths)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof DashboardStatsDTO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $totalUsers = this.getTotalUsers();
        result = result * PRIME + ($totalUsers == null ? 43 : $totalUsers.hashCode());
        final java.lang.Object $totalTeachers = this.getTotalTeachers();
        result = result * PRIME + ($totalTeachers == null ? 43 : $totalTeachers.hashCode());
        final java.lang.Object $totalStudents = this.getTotalStudents();
        result = result * PRIME + ($totalStudents == null ? 43 : $totalStudents.hashCode());
        final java.lang.Object $totalCourses = this.getTotalCourses();
        result = result * PRIME + ($totalCourses == null ? 43 : $totalCourses.hashCode());
        final java.lang.Object $totalConversations = this.getTotalConversations();
        result = result * PRIME + ($totalConversations == null ? 43 : $totalConversations.hashCode());
        final java.lang.Object $activeStudentsToday = this.getActiveStudentsToday();
        result = result * PRIME + ($activeStudentsToday == null ? 43 : $activeStudentsToday.hashCode());
        final java.lang.Object $totalKnowledgeItems = this.getTotalKnowledgeItems();
        result = result * PRIME + ($totalKnowledgeItems == null ? 43 : $totalKnowledgeItems.hashCode());
        final java.lang.Object $totalPaths = this.getTotalPaths();
        result = result * PRIME + ($totalPaths == null ? 43 : $totalPaths.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "DashboardStatsDTO(totalUsers=" + this.getTotalUsers() + ", totalTeachers=" + this.getTotalTeachers() + ", totalStudents=" + this.getTotalStudents() + ", totalCourses=" + this.getTotalCourses() + ", totalConversations=" + this.getTotalConversations() + ", activeStudentsToday=" + this.getActiveStudentsToday() + ", totalKnowledgeItems=" + this.getTotalKnowledgeItems() + ", totalPaths=" + this.getTotalPaths() + ")";
    }
}
