// Generated by delombok at Wed Jun 17 17:25:54 CST 2026
package com.edu.agent.module.admin.dto;

public class SystemConfigDTO {
    private String agentStatus;
    private String agentUrl;
    private String dbStatus;
    private String redisStatus;
    private String uptime;

    @java.lang.SuppressWarnings("all")
    public SystemConfigDTO() {
    }

    @java.lang.SuppressWarnings("all")
    public String getAgentStatus() {
        return this.agentStatus;
    }

    @java.lang.SuppressWarnings("all")
    public String getAgentUrl() {
        return this.agentUrl;
    }

    @java.lang.SuppressWarnings("all")
    public String getDbStatus() {
        return this.dbStatus;
    }

    @java.lang.SuppressWarnings("all")
    public String getRedisStatus() {
        return this.redisStatus;
    }

    @java.lang.SuppressWarnings("all")
    public String getUptime() {
        return this.uptime;
    }

    @java.lang.SuppressWarnings("all")
    public void setAgentStatus(final String agentStatus) {
        this.agentStatus = agentStatus;
    }

    @java.lang.SuppressWarnings("all")
    public void setAgentUrl(final String agentUrl) {
        this.agentUrl = agentUrl;
    }

    @java.lang.SuppressWarnings("all")
    public void setDbStatus(final String dbStatus) {
        this.dbStatus = dbStatus;
    }

    @java.lang.SuppressWarnings("all")
    public void setRedisStatus(final String redisStatus) {
        this.redisStatus = redisStatus;
    }

    @java.lang.SuppressWarnings("all")
    public void setUptime(final String uptime) {
        this.uptime = uptime;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof SystemConfigDTO)) return false;
        final SystemConfigDTO other = (SystemConfigDTO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$agentStatus = this.getAgentStatus();
        final java.lang.Object other$agentStatus = other.getAgentStatus();
        if (this$agentStatus == null ? other$agentStatus != null : !this$agentStatus.equals(other$agentStatus)) return false;
        final java.lang.Object this$agentUrl = this.getAgentUrl();
        final java.lang.Object other$agentUrl = other.getAgentUrl();
        if (this$agentUrl == null ? other$agentUrl != null : !this$agentUrl.equals(other$agentUrl)) return false;
        final java.lang.Object this$dbStatus = this.getDbStatus();
        final java.lang.Object other$dbStatus = other.getDbStatus();
        if (this$dbStatus == null ? other$dbStatus != null : !this$dbStatus.equals(other$dbStatus)) return false;
        final java.lang.Object this$redisStatus = this.getRedisStatus();
        final java.lang.Object other$redisStatus = other.getRedisStatus();
        if (this$redisStatus == null ? other$redisStatus != null : !this$redisStatus.equals(other$redisStatus)) return false;
        final java.lang.Object this$uptime = this.getUptime();
        final java.lang.Object other$uptime = other.getUptime();
        if (this$uptime == null ? other$uptime != null : !this$uptime.equals(other$uptime)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof SystemConfigDTO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $agentStatus = this.getAgentStatus();
        result = result * PRIME + ($agentStatus == null ? 43 : $agentStatus.hashCode());
        final java.lang.Object $agentUrl = this.getAgentUrl();
        result = result * PRIME + ($agentUrl == null ? 43 : $agentUrl.hashCode());
        final java.lang.Object $dbStatus = this.getDbStatus();
        result = result * PRIME + ($dbStatus == null ? 43 : $dbStatus.hashCode());
        final java.lang.Object $redisStatus = this.getRedisStatus();
        result = result * PRIME + ($redisStatus == null ? 43 : $redisStatus.hashCode());
        final java.lang.Object $uptime = this.getUptime();
        result = result * PRIME + ($uptime == null ? 43 : $uptime.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "SystemConfigDTO(agentStatus=" + this.getAgentStatus() + ", agentUrl=" + this.getAgentUrl() + ", dbStatus=" + this.getDbStatus() + ", redisStatus=" + this.getRedisStatus() + ", uptime=" + this.getUptime() + ")";
    }
}
