// Generated by delombok at Wed Jun 17 17:25:54 CST 2026
package com.edu.agent.module.learning.dto;

import java.util.List;
import java.util.Collections;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Typed response from Python Agent /agent/plan endpoint.
 * Replaces untyped Map<String, Object> to catch field-name drift at compile time.
 */
public class AgentLearningPathResponse {
    private String title;
    private String description;
    private Integer totalSteps;
    private List<Step> steps;


    public static class Step {
        private Integer order;
        private String title;
        private String description;
        @JsonProperty("knowledge_ids")
        private List<Integer> knowledgeIds;
        @JsonProperty("estimated_hours")
        private Integer estimatedHours;
        private List<String> resources;

        @java.lang.SuppressWarnings("all")
        public Step() {
        }

        @java.lang.SuppressWarnings("all")
        public Integer getOrder() {
            return this.order;
        }

        @java.lang.SuppressWarnings("all")
        public String getTitle() {
            return this.title;
        }

        @java.lang.SuppressWarnings("all")
        public String getDescription() {
            return this.description;
        }

        @java.lang.SuppressWarnings("all")
        public List<Integer> getKnowledgeIds() {
            return this.knowledgeIds;
        }

        @java.lang.SuppressWarnings("all")
        public Integer getEstimatedHours() {
            return this.estimatedHours;
        }

        @java.lang.SuppressWarnings("all")
        public List<String> getResources() {
            return this.resources;
        }

        @java.lang.SuppressWarnings("all")
        public void setOrder(final Integer order) {
            this.order = order;
        }

        @java.lang.SuppressWarnings("all")
        public void setTitle(final String title) {
            this.title = title;
        }

        @java.lang.SuppressWarnings("all")
        public void setDescription(final String description) {
            this.description = description;
        }

        @java.lang.SuppressWarnings("all")
        public void setKnowledgeIds(final List<Integer> knowledgeIds) {
            this.knowledgeIds = knowledgeIds;
        }

        @java.lang.SuppressWarnings("all")
        public void setEstimatedHours(final Integer estimatedHours) {
            this.estimatedHours = estimatedHours;
        }

        @java.lang.SuppressWarnings("all")
        public void setResources(final List<String> resources) {
            this.resources = resources;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof AgentLearningPathResponse.Step)) return false;
            final AgentLearningPathResponse.Step other = (AgentLearningPathResponse.Step) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            final java.lang.Object this$order = this.getOrder();
            final java.lang.Object other$order = other.getOrder();
            if (this$order == null ? other$order != null : !this$order.equals(other$order)) return false;
            final java.lang.Object this$estimatedHours = this.getEstimatedHours();
            final java.lang.Object other$estimatedHours = other.getEstimatedHours();
            if (this$estimatedHours == null ? other$estimatedHours != null : !this$estimatedHours.equals(other$estimatedHours)) return false;
            final java.lang.Object this$title = this.getTitle();
            final java.lang.Object other$title = other.getTitle();
            if (this$title == null ? other$title != null : !this$title.equals(other$title)) return false;
            final java.lang.Object this$description = this.getDescription();
            final java.lang.Object other$description = other.getDescription();
            if (this$description == null ? other$description != null : !this$description.equals(other$description)) return false;
            final java.lang.Object this$knowledgeIds = this.getKnowledgeIds();
            final java.lang.Object other$knowledgeIds = other.getKnowledgeIds();
            if (this$knowledgeIds == null ? other$knowledgeIds != null : !this$knowledgeIds.equals(other$knowledgeIds)) return false;
            final java.lang.Object this$resources = this.getResources();
            final java.lang.Object other$resources = other.getResources();
            if (this$resources == null ? other$resources != null : !this$resources.equals(other$resources)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof AgentLearningPathResponse.Step;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            final java.lang.Object $order = this.getOrder();
            result = result * PRIME + ($order == null ? 43 : $order.hashCode());
            final java.lang.Object $estimatedHours = this.getEstimatedHours();
            result = result * PRIME + ($estimatedHours == null ? 43 : $estimatedHours.hashCode());
            final java.lang.Object $title = this.getTitle();
            result = result * PRIME + ($title == null ? 43 : $title.hashCode());
            final java.lang.Object $description = this.getDescription();
            result = result * PRIME + ($description == null ? 43 : $description.hashCode());
            final java.lang.Object $knowledgeIds = this.getKnowledgeIds();
            result = result * PRIME + ($knowledgeIds == null ? 43 : $knowledgeIds.hashCode());
            final java.lang.Object $resources = this.getResources();
            result = result * PRIME + ($resources == null ? 43 : $resources.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "AgentLearningPathResponse.Step(order=" + this.getOrder() + ", title=" + this.getTitle() + ", description=" + this.getDescription() + ", knowledgeIds=" + this.getKnowledgeIds() + ", estimatedHours=" + this.getEstimatedHours() + ", resources=" + this.getResources() + ")";
        }
    }

    public List<Step> getStepsSafe() {
        return steps != null ? steps : Collections.emptyList();
    }

    @java.lang.SuppressWarnings("all")
    public AgentLearningPathResponse() {
    }

    @java.lang.SuppressWarnings("all")
    public String getTitle() {
        return this.title;
    }

    @java.lang.SuppressWarnings("all")
    public String getDescription() {
        return this.description;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getTotalSteps() {
        return this.totalSteps;
    }

    @java.lang.SuppressWarnings("all")
    public List<Step> getSteps() {
        return this.steps;
    }

    @java.lang.SuppressWarnings("all")
    public void setTitle(final String title) {
        this.title = title;
    }

    @java.lang.SuppressWarnings("all")
    public void setDescription(final String description) {
        this.description = description;
    }

    @java.lang.SuppressWarnings("all")
    public void setTotalSteps(final Integer totalSteps) {
        this.totalSteps = totalSteps;
    }

    @java.lang.SuppressWarnings("all")
    public void setSteps(final List<Step> steps) {
        this.steps = steps;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof AgentLearningPathResponse)) return false;
        final AgentLearningPathResponse other = (AgentLearningPathResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$totalSteps = this.getTotalSteps();
        final java.lang.Object other$totalSteps = other.getTotalSteps();
        if (this$totalSteps == null ? other$totalSteps != null : !this$totalSteps.equals(other$totalSteps)) return false;
        final java.lang.Object this$title = this.getTitle();
        final java.lang.Object other$title = other.getTitle();
        if (this$title == null ? other$title != null : !this$title.equals(other$title)) return false;
        final java.lang.Object this$description = this.getDescription();
        final java.lang.Object other$description = other.getDescription();
        if (this$description == null ? other$description != null : !this$description.equals(other$description)) return false;
        final java.lang.Object this$steps = this.getSteps();
        final java.lang.Object other$steps = other.getSteps();
        if (this$steps == null ? other$steps != null : !this$steps.equals(other$steps)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof AgentLearningPathResponse;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $totalSteps = this.getTotalSteps();
        result = result * PRIME + ($totalSteps == null ? 43 : $totalSteps.hashCode());
        final java.lang.Object $title = this.getTitle();
        result = result * PRIME + ($title == null ? 43 : $title.hashCode());
        final java.lang.Object $description = this.getDescription();
        result = result * PRIME + ($description == null ? 43 : $description.hashCode());
        final java.lang.Object $steps = this.getSteps();
        result = result * PRIME + ($steps == null ? 43 : $steps.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "AgentLearningPathResponse(title=" + this.getTitle() + ", description=" + this.getDescription() + ", totalSteps=" + this.getTotalSteps() + ", steps=" + this.getSteps() + ")";
    }
}
