// Generated by delombok at Wed Jun 17 17:25:54 CST 2026
package com.edu.agent.module.learning.dto;

import java.time.LocalDateTime;
import java.util.List;

public class LearningPathDTO {
    private Long id;
    private Long userId;
    private Long courseId;
    private String title;
    private String description;
    private Integer totalSteps;
    private Integer completedSteps;
    private Integer status; // 0=in_progress, 1=completed, 2=abandoned
    private List<LearningPathStepDTO> steps;
    private LocalDateTime createTime;

    @java.lang.SuppressWarnings("all")
    public LearningPathDTO() {
    }

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public Long getUserId() {
        return this.userId;
    }

    @java.lang.SuppressWarnings("all")
    public Long getCourseId() {
        return this.courseId;
    }

    @java.lang.SuppressWarnings("all")
    public String getTitle() {
        return this.title;
    }

    @java.lang.SuppressWarnings("all")
    public String getDescription() {
        return this.description;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getTotalSteps() {
        return this.totalSteps;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getCompletedSteps() {
        return this.completedSteps;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    public List<LearningPathStepDTO> getSteps() {
        return this.steps;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setUserId(final Long userId) {
        this.userId = userId;
    }

    @java.lang.SuppressWarnings("all")
    public void setCourseId(final Long courseId) {
        this.courseId = courseId;
    }

    @java.lang.SuppressWarnings("all")
    public void setTitle(final String title) {
        this.title = title;
    }

    @java.lang.SuppressWarnings("all")
    public void setDescription(final String description) {
        this.description = description;
    }

    @java.lang.SuppressWarnings("all")
    public void setTotalSteps(final Integer totalSteps) {
        this.totalSteps = totalSteps;
    }

    @java.lang.SuppressWarnings("all")
    public void setCompletedSteps(final Integer completedSteps) {
        this.completedSteps = completedSteps;
    }

    @java.lang.SuppressWarnings("all")
    public void setStatus(final Integer status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    public void setSteps(final List<LearningPathStepDTO> steps) {
        this.steps = steps;
    }

    @java.lang.SuppressWarnings("all")
    public void setCreateTime(final LocalDateTime createTime) {
        this.createTime = createTime;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof LearningPathDTO)) return false;
        final LearningPathDTO other = (LearningPathDTO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$userId = this.getUserId();
        final java.lang.Object other$userId = other.getUserId();
        if (this$userId == null ? other$userId != null : !this$userId.equals(other$userId)) return false;
        final java.lang.Object this$courseId = this.getCourseId();
        final java.lang.Object other$courseId = other.getCourseId();
        if (this$courseId == null ? other$courseId != null : !this$courseId.equals(other$courseId)) return false;
        final java.lang.Object this$totalSteps = this.getTotalSteps();
        final java.lang.Object other$totalSteps = other.getTotalSteps();
        if (this$totalSteps == null ? other$totalSteps != null : !this$totalSteps.equals(other$totalSteps)) return false;
        final java.lang.Object this$completedSteps = this.getCompletedSteps();
        final java.lang.Object other$completedSteps = other.getCompletedSteps();
        if (this$completedSteps == null ? other$completedSteps != null : !this$completedSteps.equals(other$completedSteps)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        final java.lang.Object this$title = this.getTitle();
        final java.lang.Object other$title = other.getTitle();
        if (this$title == null ? other$title != null : !this$title.equals(other$title)) return false;
        final java.lang.Object this$description = this.getDescription();
        final java.lang.Object other$description = other.getDescription();
        if (this$description == null ? other$description != null : !this$description.equals(other$description)) return false;
        final java.lang.Object this$steps = this.getSteps();
        final java.lang.Object other$steps = other.getSteps();
        if (this$steps == null ? other$steps != null : !this$steps.equals(other$steps)) return false;
        final java.lang.Object this$createTime = this.getCreateTime();
        final java.lang.Object other$createTime = other.getCreateTime();
        if (this$createTime == null ? other$createTime != null : !this$createTime.equals(other$createTime)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof LearningPathDTO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $userId = this.getUserId();
        result = result * PRIME + ($userId == null ? 43 : $userId.hashCode());
        final java.lang.Object $courseId = this.getCourseId();
        result = result * PRIME + ($courseId == null ? 43 : $courseId.hashCode());
        final java.lang.Object $totalSteps = this.getTotalSteps();
        result = result * PRIME + ($totalSteps == null ? 43 : $totalSteps.hashCode());
        final java.lang.Object $completedSteps = this.getCompletedSteps();
        result = result * PRIME + ($completedSteps == null ? 43 : $completedSteps.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        final java.lang.Object $title = this.getTitle();
        result = result * PRIME + ($title == null ? 43 : $title.hashCode());
        final java.lang.Object $description = this.getDescription();
        result = result * PRIME + ($description == null ? 43 : $description.hashCode());
        final java.lang.Object $steps = this.getSteps();
        result = result * PRIME + ($steps == null ? 43 : $steps.hashCode());
        final java.lang.Object $createTime = this.getCreateTime();
        result = result * PRIME + ($createTime == null ? 43 : $createTime.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "LearningPathDTO(id=" + this.getId() + ", userId=" + this.getUserId() + ", courseId=" + this.getCourseId() + ", title=" + this.getTitle() + ", description=" + this.getDescription() + ", totalSteps=" + this.getTotalSteps() + ", completedSteps=" + this.getCompletedSteps() + ", status=" + this.getStatus() + ", steps=" + this.getSteps() + ", createTime=" + this.getCreateTime() + ")";
    }
}
