// Generated by delombok at Wed Jun 17 17:25:54 CST 2026
package com.edu.agent.module.learning.dto;

import java.math.BigDecimal;

public class LearningPathStepDTO {
    private Long id;
    private Integer stepOrder;
    private String title;
    private String description;
    private Long knowledgeBaseId;
    private Integer status; // 0=pending, 1=in_progress, 2=completed

    @java.lang.SuppressWarnings("all")
    public LearningPathStepDTO() {
    }

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getStepOrder() {
        return this.stepOrder;
    }

    @java.lang.SuppressWarnings("all")
    public String getTitle() {
        return this.title;
    }

    @java.lang.SuppressWarnings("all")
    public String getDescription() {
        return this.description;
    }

    @java.lang.SuppressWarnings("all")
    public Long getKnowledgeBaseId() {
        return this.knowledgeBaseId;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setStepOrder(final Integer stepOrder) {
        this.stepOrder = stepOrder;
    }

    @java.lang.SuppressWarnings("all")
    public void setTitle(final String title) {
        this.title = title;
    }

    @java.lang.SuppressWarnings("all")
    public void setDescription(final String description) {
        this.description = description;
    }

    @java.lang.SuppressWarnings("all")
    public void setKnowledgeBaseId(final Long knowledgeBaseId) {
        this.knowledgeBaseId = knowledgeBaseId;
    }

    @java.lang.SuppressWarnings("all")
    public void setStatus(final Integer status) {
        this.status = status;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof LearningPathStepDTO)) return false;
        final LearningPathStepDTO other = (LearningPathStepDTO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$stepOrder = this.getStepOrder();
        final java.lang.Object other$stepOrder = other.getStepOrder();
        if (this$stepOrder == null ? other$stepOrder != null : !this$stepOrder.equals(other$stepOrder)) return false;
        final java.lang.Object this$knowledgeBaseId = this.getKnowledgeBaseId();
        final java.lang.Object other$knowledgeBaseId = other.getKnowledgeBaseId();
        if (this$knowledgeBaseId == null ? other$knowledgeBaseId != null : !this$knowledgeBaseId.equals(other$knowledgeBaseId)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        final java.lang.Object this$title = this.getTitle();
        final java.lang.Object other$title = other.getTitle();
        if (this$title == null ? other$title != null : !this$title.equals(other$title)) return false;
        final java.lang.Object this$description = this.getDescription();
        final java.lang.Object other$description = other.getDescription();
        if (this$description == null ? other$description != null : !this$description.equals(other$description)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof LearningPathStepDTO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $stepOrder = this.getStepOrder();
        result = result * PRIME + ($stepOrder == null ? 43 : $stepOrder.hashCode());
        final java.lang.Object $knowledgeBaseId = this.getKnowledgeBaseId();
        result = result * PRIME + ($knowledgeBaseId == null ? 43 : $knowledgeBaseId.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        final java.lang.Object $title = this.getTitle();
        result = result * PRIME + ($title == null ? 43 : $title.hashCode());
        final java.lang.Object $description = this.getDescription();
        result = result * PRIME + ($description == null ? 43 : $description.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "LearningPathStepDTO(id=" + this.getId() + ", stepOrder=" + this.getStepOrder() + ", title=" + this.getTitle() + ", description=" + this.getDescription() + ", knowledgeBaseId=" + this.getKnowledgeBaseId() + ", status=" + this.getStatus() + ")";
    }
}
