// Generated by delombok at Wed Jun 17 17:25:54 CST 2026
package com.edu.agent.module.learning.dto;

import jakarta.validation.constraints.NotNull;

public class LearningPathGenerateRequest {
    @NotNull
    private Long courseId;
    private String goal;
    private String currentLevel;

    @java.lang.SuppressWarnings("all")
    public LearningPathGenerateRequest() {
    }

    @java.lang.SuppressWarnings("all")
    public Long getCourseId() {
        return this.courseId;
    }

    @java.lang.SuppressWarnings("all")
    public String getGoal() {
        return this.goal;
    }

    @java.lang.SuppressWarnings("all")
    public String getCurrentLevel() {
        return this.currentLevel;
    }

    @java.lang.SuppressWarnings("all")
    public void setCourseId(final Long courseId) {
        this.courseId = courseId;
    }

    @java.lang.SuppressWarnings("all")
    public void setGoal(final String goal) {
        this.goal = goal;
    }

    @java.lang.SuppressWarnings("all")
    public void setCurrentLevel(final String currentLevel) {
        this.currentLevel = currentLevel;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof LearningPathGenerateRequest)) return false;
        final LearningPathGenerateRequest other = (LearningPathGenerateRequest) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$courseId = this.getCourseId();
        final java.lang.Object other$courseId = other.getCourseId();
        if (this$courseId == null ? other$courseId != null : !this$courseId.equals(other$courseId)) return false;
        final java.lang.Object this$goal = this.getGoal();
        final java.lang.Object other$goal = other.getGoal();
        if (this$goal == null ? other$goal != null : !this$goal.equals(other$goal)) return false;
        final java.lang.Object this$currentLevel = this.getCurrentLevel();
        final java.lang.Object other$currentLevel = other.getCurrentLevel();
        if (this$currentLevel == null ? other$currentLevel != null : !this$currentLevel.equals(other$currentLevel)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof LearningPathGenerateRequest;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $courseId = this.getCourseId();
        result = result * PRIME + ($courseId == null ? 43 : $courseId.hashCode());
        final java.lang.Object $goal = this.getGoal();
        result = result * PRIME + ($goal == null ? 43 : $goal.hashCode());
        final java.lang.Object $currentLevel = this.getCurrentLevel();
        result = result * PRIME + ($currentLevel == null ? 43 : $currentLevel.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "LearningPathGenerateRequest(courseId=" + this.getCourseId() + ", goal=" + this.getGoal() + ", currentLevel=" + this.getCurrentLevel() + ")";
    }
}
