// Generated by delombok at Wed Jun 17 17:25:54 CST 2026
package com.edu.agent.module.learning.dto;

import java.util.List;

public class QuestionnaireDTO {
    private Boolean isCompleted;
    // ========== 一、基础身份与背景 ==========
    private String educationLevel; // HIGH_SCHOOL / ASSOCIATE / BACHELOR / MASTER / PHD / OTHER
    private String majorDirection; // 专业方向
    private String ageRange; // UNDER_18 / 18_22 / 23_30 / 31_40 / ABOVE_40
    // ========== 二、目标与动机 ==========
    private List<String> learningGoals; // EXAM / INTEREST / EMPLOYMENT / PROMOTION / SELF_IMPROVEMENT / OTHER
    private String goalClarity; // CLEAR / VAGUE / UNDECIDED
    private String motivationLevel; // STRONG / MODERATE / WEAK
    // ========== 三、知识储备与能力现状 ==========
    private String subjectLevel; // ZERO_BASIC / BEGINNER / INTERMEDIATE / ADVANCED
    private List<String> selfStrengths; // LOGICAL / MEMORY / CREATIVITY / PRACTICAL / COMMUNICATION / MATH / LANGUAGE / PROGRAMMING
    private List<String> selfWeaknesses;// 同上选项
    // ========== 四、学习风格与偏好 ==========
    private List<String> learningMethods; // VIDEO / READING / HANDS_ON / DISCUSSION / LECTURE / QUIZ
    private List<String> studyTimeSlots; // MORNING / FORENOON / AFTERNOON / EVENING / NIGHT
    private String sessionDuration; // LESS_30MIN / 30_60MIN / 1_2HOURS / 2_4HOURS / MORE_4HOURS
    // ========== 五、元认知与自律性 ==========
    private String planningHabit; // ALWAYS / OFTEN / SOMETIMES / RARELY / NEVER
    private String focusLevel; // VERY_HIGH / HIGH / MODERATE / LOW / VERY_LOW
    private String reviewHabit; // EVERY_TIME / OFTEN / SOMETIMES / RARELY / NEVER
    // ========== 六、环境与资源支持 ==========
    private String dailyStudyHours; // LESS_1H / 1_2H / 2_4H / 4_6H / MORE_6H
    private List<String> devices; // PHONE / TABLET / LAPTOP / DESKTOP / BOOKS / NONE
    private String hasMentor; // YES / NO / WANT
    // ========== 七、心理障碍与过往失败史 ==========
    private String hasPastFailures; // YES / NO / NOT_SURE
    private List<String> mainBarriers; // LAZINESS / DISTRACTION / NO_METHOD / NO_CONFIDENCE / NO_TIME / NO_SUPPORT / BORING / ANXIETY
    private String confidenceLevel; // VERY_HIGH / HIGH / MODERATE / LOW / VERY_LOW

    @java.lang.SuppressWarnings("all")
    public QuestionnaireDTO() {
    }

    @java.lang.SuppressWarnings("all")
    public Boolean getIsCompleted() {
        return this.isCompleted;
    }

    @java.lang.SuppressWarnings("all")
    public String getEducationLevel() {
        return this.educationLevel;
    }

    @java.lang.SuppressWarnings("all")
    public String getMajorDirection() {
        return this.majorDirection;
    }

    @java.lang.SuppressWarnings("all")
    public String getAgeRange() {
        return this.ageRange;
    }

    @java.lang.SuppressWarnings("all")
    public List<String> getLearningGoals() {
        return this.learningGoals;
    }

    @java.lang.SuppressWarnings("all")
    public String getGoalClarity() {
        return this.goalClarity;
    }

    @java.lang.SuppressWarnings("all")
    public String getMotivationLevel() {
        return this.motivationLevel;
    }

    @java.lang.SuppressWarnings("all")
    public String getSubjectLevel() {
        return this.subjectLevel;
    }

    @java.lang.SuppressWarnings("all")
    public List<String> getSelfStrengths() {
        return this.selfStrengths;
    }

    @java.lang.SuppressWarnings("all")
    public List<String> getSelfWeaknesses() {
        return this.selfWeaknesses;
    }

    @java.lang.SuppressWarnings("all")
    public List<String> getLearningMethods() {
        return this.learningMethods;
    }

    @java.lang.SuppressWarnings("all")
    public List<String> getStudyTimeSlots() {
        return this.studyTimeSlots;
    }

    @java.lang.SuppressWarnings("all")
    public String getSessionDuration() {
        return this.sessionDuration;
    }

    @java.lang.SuppressWarnings("all")
    public String getPlanningHabit() {
        return this.planningHabit;
    }

    @java.lang.SuppressWarnings("all")
    public String getFocusLevel() {
        return this.focusLevel;
    }

    @java.lang.SuppressWarnings("all")
    public String getReviewHabit() {
        return this.reviewHabit;
    }

    @java.lang.SuppressWarnings("all")
    public String getDailyStudyHours() {
        return this.dailyStudyHours;
    }

    @java.lang.SuppressWarnings("all")
    public List<String> getDevices() {
        return this.devices;
    }

    @java.lang.SuppressWarnings("all")
    public String getHasMentor() {
        return this.hasMentor;
    }

    @java.lang.SuppressWarnings("all")
    public String getHasPastFailures() {
        return this.hasPastFailures;
    }

    @java.lang.SuppressWarnings("all")
    public List<String> getMainBarriers() {
        return this.mainBarriers;
    }

    @java.lang.SuppressWarnings("all")
    public String getConfidenceLevel() {
        return this.confidenceLevel;
    }

    @java.lang.SuppressWarnings("all")
    public void setIsCompleted(final Boolean isCompleted) {
        this.isCompleted = isCompleted;
    }

    @java.lang.SuppressWarnings("all")
    public void setEducationLevel(final String educationLevel) {
        this.educationLevel = educationLevel;
    }

    @java.lang.SuppressWarnings("all")
    public void setMajorDirection(final String majorDirection) {
        this.majorDirection = majorDirection;
    }

    @java.lang.SuppressWarnings("all")
    public void setAgeRange(final String ageRange) {
        this.ageRange = ageRange;
    }

    @java.lang.SuppressWarnings("all")
    public void setLearningGoals(final List<String> learningGoals) {
        this.learningGoals = learningGoals;
    }

    @java.lang.SuppressWarnings("all")
    public void setGoalClarity(final String goalClarity) {
        this.goalClarity = goalClarity;
    }

    @java.lang.SuppressWarnings("all")
    public void setMotivationLevel(final String motivationLevel) {
        this.motivationLevel = motivationLevel;
    }

    @java.lang.SuppressWarnings("all")
    public void setSubjectLevel(final String subjectLevel) {
        this.subjectLevel = subjectLevel;
    }

    @java.lang.SuppressWarnings("all")
    public void setSelfStrengths(final List<String> selfStrengths) {
        this.selfStrengths = selfStrengths;
    }

    @java.lang.SuppressWarnings("all")
    public void setSelfWeaknesses(final List<String> selfWeaknesses) {
        this.selfWeaknesses = selfWeaknesses;
    }

    @java.lang.SuppressWarnings("all")
    public void setLearningMethods(final List<String> learningMethods) {
        this.learningMethods = learningMethods;
    }

    @java.lang.SuppressWarnings("all")
    public void setStudyTimeSlots(final List<String> studyTimeSlots) {
        this.studyTimeSlots = studyTimeSlots;
    }

    @java.lang.SuppressWarnings("all")
    public void setSessionDuration(final String sessionDuration) {
        this.sessionDuration = sessionDuration;
    }

    @java.lang.SuppressWarnings("all")
    public void setPlanningHabit(final String planningHabit) {
        this.planningHabit = planningHabit;
    }

    @java.lang.SuppressWarnings("all")
    public void setFocusLevel(final String focusLevel) {
        this.focusLevel = focusLevel;
    }

    @java.lang.SuppressWarnings("all")
    public void setReviewHabit(final String reviewHabit) {
        this.reviewHabit = reviewHabit;
    }

    @java.lang.SuppressWarnings("all")
    public void setDailyStudyHours(final String dailyStudyHours) {
        this.dailyStudyHours = dailyStudyHours;
    }

    @java.lang.SuppressWarnings("all")
    public void setDevices(final List<String> devices) {
        this.devices = devices;
    }

    @java.lang.SuppressWarnings("all")
    public void setHasMentor(final String hasMentor) {
        this.hasMentor = hasMentor;
    }

    @java.lang.SuppressWarnings("all")
    public void setHasPastFailures(final String hasPastFailures) {
        this.hasPastFailures = hasPastFailures;
    }

    @java.lang.SuppressWarnings("all")
    public void setMainBarriers(final List<String> mainBarriers) {
        this.mainBarriers = mainBarriers;
    }

    @java.lang.SuppressWarnings("all")
    public void setConfidenceLevel(final String confidenceLevel) {
        this.confidenceLevel = confidenceLevel;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof QuestionnaireDTO)) return false;
        final QuestionnaireDTO other = (QuestionnaireDTO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$isCompleted = this.getIsCompleted();
        final java.lang.Object other$isCompleted = other.getIsCompleted();
        if (this$isCompleted == null ? other$isCompleted != null : !this$isCompleted.equals(other$isCompleted)) return false;
        final java.lang.Object this$educationLevel = this.getEducationLevel();
        final java.lang.Object other$educationLevel = other.getEducationLevel();
        if (this$educationLevel == null ? other$educationLevel != null : !this$educationLevel.equals(other$educationLevel)) return false;
        final java.lang.Object this$majorDirection = this.getMajorDirection();
        final java.lang.Object other$majorDirection = other.getMajorDirection();
        if (this$majorDirection == null ? other$majorDirection != null : !this$majorDirection.equals(other$majorDirection)) return false;
        final java.lang.Object this$ageRange = this.getAgeRange();
        final java.lang.Object other$ageRange = other.getAgeRange();
        if (this$ageRange == null ? other$ageRange != null : !this$ageRange.equals(other$ageRange)) return false;
        final java.lang.Object this$learningGoals = this.getLearningGoals();
        final java.lang.Object other$learningGoals = other.getLearningGoals();
        if (this$learningGoals == null ? other$learningGoals != null : !this$learningGoals.equals(other$learningGoals)) return false;
        final java.lang.Object this$goalClarity = this.getGoalClarity();
        final java.lang.Object other$goalClarity = other.getGoalClarity();
        if (this$goalClarity == null ? other$goalClarity != null : !this$goalClarity.equals(other$goalClarity)) return false;
        final java.lang.Object this$motivationLevel = this.getMotivationLevel();
        final java.lang.Object other$motivationLevel = other.getMotivationLevel();
        if (this$motivationLevel == null ? other$motivationLevel != null : !this$motivationLevel.equals(other$motivationLevel)) return false;
        final java.lang.Object this$subjectLevel = this.getSubjectLevel();
        final java.lang.Object other$subjectLevel = other.getSubjectLevel();
        if (this$subjectLevel == null ? other$subjectLevel != null : !this$subjectLevel.equals(other$subjectLevel)) return false;
        final java.lang.Object this$selfStrengths = this.getSelfStrengths();
        final java.lang.Object other$selfStrengths = other.getSelfStrengths();
        if (this$selfStrengths == null ? other$selfStrengths != null : !this$selfStrengths.equals(other$selfStrengths)) return false;
        final java.lang.Object this$selfWeaknesses = this.getSelfWeaknesses();
        final java.lang.Object other$selfWeaknesses = other.getSelfWeaknesses();
        if (this$selfWeaknesses == null ? other$selfWeaknesses != null : !this$selfWeaknesses.equals(other$selfWeaknesses)) return false;
        final java.lang.Object this$learningMethods = this.getLearningMethods();
        final java.lang.Object other$learningMethods = other.getLearningMethods();
        if (this$learningMethods == null ? other$learningMethods != null : !this$learningMethods.equals(other$learningMethods)) return false;
        final java.lang.Object this$studyTimeSlots = this.getStudyTimeSlots();
        final java.lang.Object other$studyTimeSlots = other.getStudyTimeSlots();
        if (this$studyTimeSlots == null ? other$studyTimeSlots != null : !this$studyTimeSlots.equals(other$studyTimeSlots)) return false;
        final java.lang.Object this$sessionDuration = this.getSessionDuration();
        final java.lang.Object other$sessionDuration = other.getSessionDuration();
        if (this$sessionDuration == null ? other$sessionDuration != null : !this$sessionDuration.equals(other$sessionDuration)) return false;
        final java.lang.Object this$planningHabit = this.getPlanningHabit();
        final java.lang.Object other$planningHabit = other.getPlanningHabit();
        if (this$planningHabit == null ? other$planningHabit != null : !this$planningHabit.equals(other$planningHabit)) return false;
        final java.lang.Object this$focusLevel = this.getFocusLevel();
        final java.lang.Object other$focusLevel = other.getFocusLevel();
        if (this$focusLevel == null ? other$focusLevel != null : !this$focusLevel.equals(other$focusLevel)) return false;
        final java.lang.Object this$reviewHabit = this.getReviewHabit();
        final java.lang.Object other$reviewHabit = other.getReviewHabit();
        if (this$reviewHabit == null ? other$reviewHabit != null : !this$reviewHabit.equals(other$reviewHabit)) return false;
        final java.lang.Object this$dailyStudyHours = this.getDailyStudyHours();
        final java.lang.Object other$dailyStudyHours = other.getDailyStudyHours();
        if (this$dailyStudyHours == null ? other$dailyStudyHours != null : !this$dailyStudyHours.equals(other$dailyStudyHours)) return false;
        final java.lang.Object this$devices = this.getDevices();
        final java.lang.Object other$devices = other.getDevices();
        if (this$devices == null ? other$devices != null : !this$devices.equals(other$devices)) return false;
        final java.lang.Object this$hasMentor = this.getHasMentor();
        final java.lang.Object other$hasMentor = other.getHasMentor();
        if (this$hasMentor == null ? other$hasMentor != null : !this$hasMentor.equals(other$hasMentor)) return false;
        final java.lang.Object this$hasPastFailures = this.getHasPastFailures();
        final java.lang.Object other$hasPastFailures = other.getHasPastFailures();
        if (this$hasPastFailures == null ? other$hasPastFailures != null : !this$hasPastFailures.equals(other$hasPastFailures)) return false;
        final java.lang.Object this$mainBarriers = this.getMainBarriers();
        final java.lang.Object other$mainBarriers = other.getMainBarriers();
        if (this$mainBarriers == null ? other$mainBarriers != null : !this$mainBarriers.equals(other$mainBarriers)) return false;
        final java.lang.Object this$confidenceLevel = this.getConfidenceLevel();
        final java.lang.Object other$confidenceLevel = other.getConfidenceLevel();
        if (this$confidenceLevel == null ? other$confidenceLevel != null : !this$confidenceLevel.equals(other$confidenceLevel)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof QuestionnaireDTO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $isCompleted = this.getIsCompleted();
        result = result * PRIME + ($isCompleted == null ? 43 : $isCompleted.hashCode());
        final java.lang.Object $educationLevel = this.getEducationLevel();
        result = result * PRIME + ($educationLevel == null ? 43 : $educationLevel.hashCode());
        final java.lang.Object $majorDirection = this.getMajorDirection();
        result = result * PRIME + ($majorDirection == null ? 43 : $majorDirection.hashCode());
        final java.lang.Object $ageRange = this.getAgeRange();
        result = result * PRIME + ($ageRange == null ? 43 : $ageRange.hashCode());
        final java.lang.Object $learningGoals = this.getLearningGoals();
        result = result * PRIME + ($learningGoals == null ? 43 : $learningGoals.hashCode());
        final java.lang.Object $goalClarity = this.getGoalClarity();
        result = result * PRIME + ($goalClarity == null ? 43 : $goalClarity.hashCode());
        final java.lang.Object $motivationLevel = this.getMotivationLevel();
        result = result * PRIME + ($motivationLevel == null ? 43 : $motivationLevel.hashCode());
        final java.lang.Object $subjectLevel = this.getSubjectLevel();
        result = result * PRIME + ($subjectLevel == null ? 43 : $subjectLevel.hashCode());
        final java.lang.Object $selfStrengths = this.getSelfStrengths();
        result = result * PRIME + ($selfStrengths == null ? 43 : $selfStrengths.hashCode());
        final java.lang.Object $selfWeaknesses = this.getSelfWeaknesses();
        result = result * PRIME + ($selfWeaknesses == null ? 43 : $selfWeaknesses.hashCode());
        final java.lang.Object $learningMethods = this.getLearningMethods();
        result = result * PRIME + ($learningMethods == null ? 43 : $learningMethods.hashCode());
        final java.lang.Object $studyTimeSlots = this.getStudyTimeSlots();
        result = result * PRIME + ($studyTimeSlots == null ? 43 : $studyTimeSlots.hashCode());
        final java.lang.Object $sessionDuration = this.getSessionDuration();
        result = result * PRIME + ($sessionDuration == null ? 43 : $sessionDuration.hashCode());
        final java.lang.Object $planningHabit = this.getPlanningHabit();
        result = result * PRIME + ($planningHabit == null ? 43 : $planningHabit.hashCode());
        final java.lang.Object $focusLevel = this.getFocusLevel();
        result = result * PRIME + ($focusLevel == null ? 43 : $focusLevel.hashCode());
        final java.lang.Object $reviewHabit = this.getReviewHabit();
        result = result * PRIME + ($reviewHabit == null ? 43 : $reviewHabit.hashCode());
        final java.lang.Object $dailyStudyHours = this.getDailyStudyHours();
        result = result * PRIME + ($dailyStudyHours == null ? 43 : $dailyStudyHours.hashCode());
        final java.lang.Object $devices = this.getDevices();
        result = result * PRIME + ($devices == null ? 43 : $devices.hashCode());
        final java.lang.Object $hasMentor = this.getHasMentor();
        result = result * PRIME + ($hasMentor == null ? 43 : $hasMentor.hashCode());
        final java.lang.Object $hasPastFailures = this.getHasPastFailures();
        result = result * PRIME + ($hasPastFailures == null ? 43 : $hasPastFailures.hashCode());
        final java.lang.Object $mainBarriers = this.getMainBarriers();
        result = result * PRIME + ($mainBarriers == null ? 43 : $mainBarriers.hashCode());
        final java.lang.Object $confidenceLevel = this.getConfidenceLevel();
        result = result * PRIME + ($confidenceLevel == null ? 43 : $confidenceLevel.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "QuestionnaireDTO(isCompleted=" + this.getIsCompleted() + ", educationLevel=" + this.getEducationLevel() + ", majorDirection=" + this.getMajorDirection() + ", ageRange=" + this.getAgeRange() + ", learningGoals=" + this.getLearningGoals() + ", goalClarity=" + this.getGoalClarity() + ", motivationLevel=" + this.getMotivationLevel() + ", subjectLevel=" + this.getSubjectLevel() + ", selfStrengths=" + this.getSelfStrengths() + ", selfWeaknesses=" + this.getSelfWeaknesses() + ", learningMethods=" + this.getLearningMethods() + ", studyTimeSlots=" + this.getStudyTimeSlots() + ", sessionDuration=" + this.getSessionDuration() + ", planningHabit=" + this.getPlanningHabit() + ", focusLevel=" + this.getFocusLevel() + ", reviewHabit=" + this.getReviewHabit() + ", dailyStudyHours=" + this.getDailyStudyHours() + ", devices=" + this.getDevices() + ", hasMentor=" + this.getHasMentor() + ", hasPastFailures=" + this.getHasPastFailures() + ", mainBarriers=" + this.getMainBarriers() + ", confidenceLevel=" + this.getConfidenceLevel() + ")";
    }
}
